// @generated by crates/xui-icons/assets/generate.py from assets/aero/svg/*.svg.
// Do not edit by hand.

#[allow(unused_imports)] // not every category draws a translucent colour
use xui_core::backend::{PathSeg, Rgba};

use super::gradients;
use crate::shape::{Paint, Shape};

pub(super) const FOLDER: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.5, 8.0), PathSeg::CubicTo(3.5, 6.9, 4.4, 6.0, 5.5, 6.0), PathSeg::LineTo(12.5, 6.0), PathSeg::LineTo(15.5, 9.0), PathSeg::LineTo(27.5, 9.0), PathSeg::CubicTo(28.6, 9.0, 29.5, 9.9, 29.5, 11.0), PathSeg::LineTo(29.5, 25.0), PathSeg::CubicTo(29.5, 26.1, 28.6, 27.0, 27.5, 27.0), PathSeg::LineTo(5.5, 27.0), PathSeg::CubicTo(4.4, 27.0, 3.5, 26.1, 3.5, 25.0), PathSeg::Close], Paint::Gradient(&gradients::ORANGE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(3.5, 13.5), PathSeg::CubicTo(3.5, 12.4, 4.4, 11.5, 5.5, 11.5), PathSeg::LineTo(26.5, 11.5), PathSeg::CubicTo(27.6, 11.5, 28.5, 12.4, 28.5, 13.5), PathSeg::LineTo(28.5, 25.5), PathSeg::CubicTo(28.5, 26.6, 27.6, 27.5, 26.5, 27.5), PathSeg::LineTo(5.5, 27.5), PathSeg::CubicTo(4.4, 27.5, 3.5, 26.6, 3.5, 25.5), PathSeg::Close], Paint::Gradient(&gradients::YELLOW), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(5.5, 12.0), PathSeg::LineTo(26.5, 12.0), PathSeg::CubicTo(27.3, 12.0, 28.0, 12.6, 28.0, 13.5), PathSeg::LineTo(28.0, 16.0), PathSeg::CubicTo(20.0, 18.5, 12.0, 18.5, 4.0, 16.0), PathSeg::LineTo(4.0, 13.5), PathSeg::CubicTo(4.0, 12.6, 4.7, 12.0, 5.5, 12.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];

pub(super) const FOLDER_OPEN: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.5, 8.0), PathSeg::CubicTo(3.5, 6.9, 4.4, 6.0, 5.5, 6.0), PathSeg::LineTo(12.5, 6.0), PathSeg::LineTo(15.5, 9.0), PathSeg::LineTo(25.5, 9.0), PathSeg::CubicTo(26.6, 9.0, 27.5, 9.9, 27.5, 11.0), PathSeg::LineTo(27.5, 27.0), PathSeg::LineTo(3.5, 27.0), PathSeg::Close], Paint::Gradient(&gradients::ORANGE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(8.0, 9.0), PathSeg::LineTo(23.0, 9.0), PathSeg::LineTo(23.0, 16.0), PathSeg::LineTo(8.0, 16.0), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(2.5, 27.5), PathSeg::LineTo(6.0, 14.0), PathSeg::LineTo(30.0, 14.0), PathSeg::LineTo(26.5, 27.5), PathSeg::Close], Paint::Gradient(&gradients::YELLOW), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(6.6, 14.0), PathSeg::LineTo(29.5, 14.0), PathSeg::LineTo(28.6, 17.3), PathSeg::CubicTo(21.6, 19.3, 12.6, 19.3, 4.6, 17.3), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];

pub(super) const DOCUMENT: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(7.5, 3.5), PathSeg::LineTo(20.5, 3.5), PathSeg::LineTo(25.5, 8.5), PathSeg::LineTo(25.5, 28.5), PathSeg::LineTo(7.5, 28.5), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(20.5, 3.5), PathSeg::LineTo(20.5, 8.5), PathSeg::LineTo(25.5, 8.5), PathSeg::Close], Paint::Gradient(&gradients::SILVER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(11.0, 14.0), PathSeg::LineTo(22.0, 14.0), PathSeg::MoveTo(11.0, 17.5), PathSeg::LineTo(22.0, 17.5), PathSeg::MoveTo(11.0, 21.0), PathSeg::LineTo(18.0, 21.0)], Paint::Color(Rgba::rgb(90, 143, 208)), 1.0),
    Shape::fill(&[PathSeg::MoveTo(7.5, 3.5), PathSeg::LineTo(20.5, 3.5), PathSeg::LineTo(25.5, 8.5), PathSeg::LineTo(25.5, 12.5), PathSeg::CubicTo(19.5, 14.5, 13.5, 14.5, 7.5, 12.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(102),
];

pub(super) const IMAGE: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.0, 6.5), PathSeg::LineTo(27.0, 6.5), PathSeg::CubicTo(27.83, 6.5, 28.5, 7.17, 28.5, 8.0), PathSeg::LineTo(28.5, 24.0), PathSeg::CubicTo(28.5, 24.83, 27.83, 25.5, 27.0, 25.5), PathSeg::LineTo(5.0, 25.5), PathSeg::CubicTo(4.17, 25.5, 3.5, 24.83, 3.5, 24.0), PathSeg::LineTo(3.5, 8.0), PathSeg::CubicTo(3.5, 7.17, 4.17, 6.5, 5.0, 6.5), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(6.0, 9.0), PathSeg::LineTo(26.0, 9.0), PathSeg::LineTo(26.0, 23.0), PathSeg::LineTo(6.0, 23.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE)),
    Shape::fill(&[PathSeg::MoveTo(6.0, 23.0), PathSeg::LineTo(6.0, 19.0), PathSeg::CubicTo(11.0, 15.0, 15.0, 18.0, 19.0, 16.0), PathSeg::CubicTo(22.0, 14.5, 24.0, 16.0, 26.0, 17.0), PathSeg::LineTo(26.0, 23.0), PathSeg::Close], Paint::Gradient(&gradients::GREEN)),
    Shape::both(&[PathSeg::MoveTo(18.5, 13.5), PathSeg::CubicTo(18.5, 12.12, 19.62, 11.0, 21.0, 11.0), PathSeg::CubicTo(22.38, 11.0, 23.5, 12.12, 23.5, 13.5), PathSeg::CubicTo(23.5, 14.88, 22.38, 16.0, 21.0, 16.0), PathSeg::CubicTo(19.62, 16.0, 18.5, 14.88, 18.5, 13.5), PathSeg::Close], Paint::Gradient(&gradients::ORANGE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(6.0, 9.0), PathSeg::LineTo(26.0, 9.0), PathSeg::LineTo(26.0, 13.0), PathSeg::CubicTo(18.0, 16.0, 12.0, 16.0, 6.0, 19.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(115),
];

pub(super) const MUSIC: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(13.5, 8.5), PathSeg::LineTo(13.5, 23.0), PathSeg::MoveTo(26.5, 5.5), PathSeg::LineTo(26.5, 19.5)], Paint::Color(Rgba::with_alpha(10, 42, 85, 191)), 1.4),
    Shape::both(&[PathSeg::MoveTo(13.5, 6.5), PathSeg::LineTo(26.5, 3.5), PathSeg::LineTo(26.5, 8.5), PathSeg::LineTo(13.5, 11.5), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(6.0, 24.0), PathSeg::CubicTo(6.0, 22.34, 7.79, 21.0, 10.0, 21.0), PathSeg::CubicTo(12.21, 21.0, 14.0, 22.34, 14.0, 24.0), PathSeg::CubicTo(14.0, 25.66, 12.21, 27.0, 10.0, 27.0), PathSeg::CubicTo(7.79, 27.0, 6.0, 25.66, 6.0, 24.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(19.0, 21.0), PathSeg::CubicTo(19.0, 19.34, 20.79, 18.0, 23.0, 18.0), PathSeg::CubicTo(25.21, 18.0, 27.0, 19.34, 27.0, 21.0), PathSeg::CubicTo(27.0, 22.66, 25.21, 24.0, 23.0, 24.0), PathSeg::CubicTo(20.79, 24.0, 19.0, 22.66, 19.0, 21.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(7.0, 23.0), PathSeg::CubicTo(7.0, 22.39, 7.9, 21.9, 9.0, 21.9), PathSeg::CubicTo(10.1, 21.9, 11.0, 22.39, 11.0, 23.0), PathSeg::CubicTo(11.0, 23.61, 10.1, 24.1, 9.0, 24.1), PathSeg::CubicTo(7.9, 24.1, 7.0, 23.61, 7.0, 23.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(204),
    Shape::fill(&[PathSeg::MoveTo(20.0, 20.0), PathSeg::CubicTo(20.0, 19.39, 20.9, 18.9, 22.0, 18.9), PathSeg::CubicTo(23.1, 18.9, 24.0, 19.39, 24.0, 20.0), PathSeg::CubicTo(24.0, 20.61, 23.1, 21.1, 22.0, 21.1), PathSeg::CubicTo(20.9, 21.1, 20.0, 20.61, 20.0, 20.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(204),
];

pub(super) const ARCHIVE: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(6.5, 7.5), PathSeg::LineTo(25.5, 7.5), PathSeg::CubicTo(26.6, 7.5, 27.5, 8.4, 27.5, 9.5), PathSeg::LineTo(27.5, 25.5), PathSeg::CubicTo(27.5, 26.6, 26.6, 27.5, 25.5, 27.5), PathSeg::LineTo(6.5, 27.5), PathSeg::CubicTo(5.4, 27.5, 4.5, 26.6, 4.5, 25.5), PathSeg::LineTo(4.5, 9.5), PathSeg::CubicTo(4.5, 8.4, 5.4, 7.5, 6.5, 7.5), PathSeg::Close], Paint::Gradient(&gradients::ORANGE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(5.5, 4.5), PathSeg::LineTo(26.5, 4.5), PathSeg::CubicTo(27.6, 4.5, 28.5, 5.4, 28.5, 6.5), PathSeg::LineTo(28.5, 9.5), PathSeg::CubicTo(28.5, 10.6, 27.6, 11.5, 26.5, 11.5), PathSeg::LineTo(5.5, 11.5), PathSeg::CubicTo(4.4, 11.5, 3.5, 10.6, 3.5, 9.5), PathSeg::LineTo(3.5, 6.5), PathSeg::CubicTo(3.5, 5.4, 4.4, 4.5, 5.5, 4.5), PathSeg::Close], Paint::Gradient(&gradients::YELLOW), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(13.5, 14.0), PathSeg::LineTo(18.5, 14.0), PathSeg::CubicTo(19.33, 14.0, 20.0, 14.67, 20.0, 15.5), PathSeg::LineTo(20.0, 15.5), PathSeg::CubicTo(20.0, 16.33, 19.33, 17.0, 18.5, 17.0), PathSeg::LineTo(13.5, 17.0), PathSeg::CubicTo(12.67, 17.0, 12.0, 16.33, 12.0, 15.5), PathSeg::LineTo(12.0, 15.5), PathSeg::CubicTo(12.0, 14.67, 12.67, 14.0, 13.5, 14.0), PathSeg::Close], Paint::Gradient(&gradients::DARK), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(6.0, 5.2), PathSeg::LineTo(26.0, 5.2), PathSeg::CubicTo(26.83, 5.2, 27.5, 5.87, 27.5, 6.7), PathSeg::LineTo(27.5, 7.1), PathSeg::CubicTo(27.5, 7.93, 26.83, 8.6, 26.0, 8.6), PathSeg::LineTo(6.0, 8.6), PathSeg::CubicTo(5.17, 8.6, 4.5, 7.93, 4.5, 7.1), PathSeg::LineTo(4.5, 6.7), PathSeg::CubicTo(4.5, 5.87, 5.17, 5.2, 6.0, 5.2), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];
