// @generated by crates/xui-icons/assets/generate.py from assets/aero/svg/*.svg.
// Do not edit by hand.

use xui_core::backend::{GradientStop, Rgba};

use crate::gradient::Gradient;

pub(super) static BLUE: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(157, 220, 255, 255)), GradientStop::new(0.5, Rgba::with_alpha(58, 157, 240, 255)), GradientStop::new(1.0, Rgba::with_alpha(15, 91, 194, 255))]);
pub(super) static GREEN: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(198, 245, 138, 255)), GradientStop::new(0.5, Rgba::with_alpha(92, 194, 58, 255)), GradientStop::new(1.0, Rgba::with_alpha(35, 134, 31, 255))]);
pub(super) static ORANGE: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(255, 224, 138, 255)), GradientStop::new(0.5, Rgba::with_alpha(255, 169, 40, 255)), GradientStop::new(1.0, Rgba::with_alpha(224, 112, 10, 255))]);
pub(super) static RED: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(255, 160, 140, 255)), GradientStop::new(0.5, Rgba::with_alpha(238, 74, 54, 255)), GradientStop::new(1.0, Rgba::with_alpha(181, 22, 15, 255))]);
pub(super) static YELLOW: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(255, 241, 176, 255)), GradientStop::new(0.5, Rgba::with_alpha(255, 209, 74, 255)), GradientStop::new(1.0, Rgba::with_alpha(233, 163, 23, 255))]);
pub(super) static TEAL: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(165, 240, 255, 255)), GradientStop::new(0.5, Rgba::with_alpha(33, 198, 216, 255)), GradientStop::new(1.0, Rgba::with_alpha(10, 122, 149, 255))]);
pub(super) static SILVER: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(255, 255, 255, 255)), GradientStop::new(0.55, Rgba::with_alpha(216, 225, 234, 255)), GradientStop::new(1.0, Rgba::with_alpha(154, 169, 184, 255))]);
pub(super) static DARK: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(134, 150, 168, 255)), GradientStop::new(0.45, Rgba::with_alpha(60, 74, 90, 255)), GradientStop::new(1.0, Rgba::with_alpha(28, 37, 48, 255))]);
pub(super) static GLASS: Gradient = Gradient::new((0.0, 0.0), (1.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(47, 143, 230, 255)), GradientStop::new(1.0, Rgba::with_alpha(11, 53, 102, 255))]);
pub(super) static PAPER: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(255, 255, 255, 255)), GradientStop::new(1.0, Rgba::with_alpha(221, 232, 244, 255))]);
pub(super) static RAIN: Gradient = Gradient::new((0.0, 0.0), (1.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(79, 216, 255, 255)), GradientStop::new(0.35, Rgba::with_alpha(255, 106, 213, 255)), GradientStop::new(0.7, Rgba::with_alpha(255, 225, 74, 255)), GradientStop::new(1.0, Rgba::with_alpha(79, 216, 255, 255))]);
pub(super) static GLOSS: Gradient = Gradient::new((0.0, 0.0), (0.0, 1.0), &[GradientStop::new(0.0, Rgba::with_alpha(255, 255, 255, 230)), GradientStop::new(1.0, Rgba::with_alpha(255, 255, 255, 20))]);
