// @generated by crates/xui-icons/assets/generate.py from assets/aero/svg/*.svg.
// Do not edit by hand.

#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod files;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod gradients;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod hardware;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod system;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod toolkit;

use crate::icon::Icon;
use crate::shape::Shape;

/// The shapes of `icon` in this style.
pub(crate) fn shapes(icon: Icon) -> &'static [Shape] {
    match icon {
        Icon::Computer => hardware::COMPUTER,
        Icon::Monitor => hardware::MONITOR,
        Icon::Keyboard => hardware::KEYBOARD,
        Icon::Mouse => hardware::MOUSE,
        Icon::HardDisk => hardware::HARD_DISK,
        Icon::Floppy => hardware::FLOPPY,
        Icon::CdRom => hardware::CD_ROM,
        Icon::Printer => hardware::PRINTER,
        Icon::Modem => hardware::MODEM,
        Icon::Network => hardware::NETWORK,
        Icon::Server => hardware::SERVER,
        Icon::Speaker => hardware::SPEAKER,
        Icon::Folder => files::FOLDER,
        Icon::FolderOpen => files::FOLDER_OPEN,
        Icon::Document => files::DOCUMENT,
        Icon::Image => files::IMAGE,
        Icon::Music => files::MUSIC,
        Icon::Archive => files::ARCHIVE,
        Icon::Trash => system::TRASH,
        Icon::TrashFull => system::TRASH_FULL,
        Icon::Settings => system::SETTINGS,
        Icon::Search => system::SEARCH,
        Icon::Home => system::HOME,
        Icon::Clock => system::CLOCK,
        Icon::Mail => system::MAIL,
        Icon::Lock => system::LOCK,
        Icon::Help => system::HELP,
        Icon::Warning => system::WARNING,
        Icon::Info => system::INFO,
        Icon::Error => system::ERROR,
        Icon::Rpc => toolkit::RPC,
        Icon::PubSub => toolkit::PUB_SUB,
        Icon::Theme => toolkit::THEME,
        Icon::Widget => toolkit::WIDGET,
        Icon::Terminal => toolkit::TERMINAL,
        Icon::Window => toolkit::WINDOW,
    }
}
