// @generated by crates/xui-icons/assets/generate.py from assets/aero/svg/*.svg.
// Do not edit by hand.

#[allow(unused_imports)] // not every category draws a translucent colour
use xui_core::backend::{PathSeg, Rgba};

use super::gradients;
use crate::shape::{Paint, Shape};

pub(super) const TRASH: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(13.0, 6.5), PathSeg::LineTo(13.0, 4.5), PathSeg::LineTo(19.0, 4.5), PathSeg::LineTo(19.0, 6.5)], Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(8.5, 10.5), PathSeg::LineTo(23.5, 10.5), PathSeg::LineTo(22.0, 27.5), PathSeg::CubicTo(21.9, 28.25, 21.26, 28.81, 20.5, 28.8), PathSeg::LineTo(11.5, 28.8), PathSeg::CubicTo(10.74, 28.81, 10.1, 28.25, 10.0, 27.5), PathSeg::Close], Paint::Color(Rgba::with_alpha(191, 230, 255, 153)), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(13.0, 14.0), PathSeg::LineTo(13.5, 25.0), PathSeg::MoveTo(16.0, 14.0), PathSeg::LineTo(16.0, 25.0), PathSeg::MoveTo(19.0, 14.0), PathSeg::LineTo(18.5, 25.0)], Paint::Color(Rgba::with_alpha(255, 255, 255, 217)), 0.9),
    Shape::both(&[PathSeg::MoveTo(8.0, 6.5), PathSeg::LineTo(24.0, 6.5), PathSeg::CubicTo(25.1, 6.5, 26.0, 7.4, 26.0, 8.5), PathSeg::LineTo(26.0, 8.5), PathSeg::CubicTo(26.0, 9.6, 25.1, 10.5, 24.0, 10.5), PathSeg::LineTo(8.0, 10.5), PathSeg::CubicTo(6.9, 10.5, 6.0, 9.6, 6.0, 8.5), PathSeg::LineTo(6.0, 8.5), PathSeg::CubicTo(6.0, 7.4, 6.9, 6.5, 8.0, 6.5), PathSeg::Close], Paint::Gradient(&gradients::SILVER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(10.0, 11.5), PathSeg::LineTo(14.0, 11.5), PathSeg::LineTo(13.2, 25.5), PathSeg::LineTo(11.6, 25.5), PathSeg::Close], Paint::Color(Rgba::rgb(255, 255, 255))).opacity(128),
];

pub(super) const TRASH_FULL: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(10.0, 8.0), PathSeg::LineTo(11.5, 2.5), PathSeg::LineTo(15.5, 5.0), PathSeg::LineTo(18.5, 1.0), PathSeg::LineTo(22.0, 6.5), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(8.5, 10.5), PathSeg::LineTo(23.5, 10.5), PathSeg::LineTo(22.0, 27.5), PathSeg::CubicTo(21.9, 28.25, 21.26, 28.81, 20.5, 28.8), PathSeg::LineTo(11.5, 28.8), PathSeg::CubicTo(10.74, 28.81, 10.1, 28.25, 10.0, 27.5), PathSeg::Close], Paint::Color(Rgba::with_alpha(191, 230, 255, 153)), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(13.0, 14.0), PathSeg::LineTo(13.5, 25.0), PathSeg::MoveTo(16.0, 14.0), PathSeg::LineTo(16.0, 25.0), PathSeg::MoveTo(19.0, 14.0), PathSeg::LineTo(18.5, 25.0)], Paint::Color(Rgba::with_alpha(255, 255, 255, 217)), 0.9),
    Shape::both(&[PathSeg::MoveTo(8.0, 6.5), PathSeg::LineTo(24.0, 6.5), PathSeg::CubicTo(25.1, 6.5, 26.0, 7.4, 26.0, 8.5), PathSeg::LineTo(26.0, 8.5), PathSeg::CubicTo(26.0, 9.6, 25.1, 10.5, 24.0, 10.5), PathSeg::LineTo(8.0, 10.5), PathSeg::CubicTo(6.9, 10.5, 6.0, 9.6, 6.0, 8.5), PathSeg::LineTo(6.0, 8.5), PathSeg::CubicTo(6.0, 7.4, 6.9, 6.5, 8.0, 6.5), PathSeg::Close], Paint::Gradient(&gradients::SILVER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(10.0, 11.5), PathSeg::LineTo(14.0, 11.5), PathSeg::LineTo(13.2, 25.5), PathSeg::LineTo(11.6, 25.5), PathSeg::Close], Paint::Color(Rgba::rgb(255, 255, 255))).opacity(128),
];

pub(super) const SETTINGS: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(26.5, 12.7), PathSeg::LineTo(29.7, 13.2), PathSeg::LineTo(29.7, 18.8), PathSeg::LineTo(26.5, 19.3), PathSeg::LineTo(25.7, 21.1), PathSeg::LineTo(27.7, 23.7), PathSeg::LineTo(23.7, 27.7), PathSeg::LineTo(21.1, 25.7), PathSeg::LineTo(19.3, 26.5), PathSeg::LineTo(18.8, 29.7), PathSeg::LineTo(13.2, 29.7), PathSeg::LineTo(12.7, 26.5), PathSeg::LineTo(10.9, 25.7), PathSeg::LineTo(8.3, 27.7), PathSeg::LineTo(4.3, 23.7), PathSeg::LineTo(6.3, 21.1), PathSeg::LineTo(5.5, 19.3), PathSeg::LineTo(2.3, 18.8), PathSeg::LineTo(2.3, 13.2), PathSeg::LineTo(5.5, 12.7), PathSeg::LineTo(6.3, 10.9), PathSeg::LineTo(4.3, 8.3), PathSeg::LineTo(8.3, 4.3), PathSeg::LineTo(10.9, 6.3), PathSeg::LineTo(12.7, 5.5), PathSeg::LineTo(13.2, 2.3), PathSeg::LineTo(18.8, 2.3), PathSeg::LineTo(19.3, 5.5), PathSeg::LineTo(21.1, 6.3), PathSeg::LineTo(23.7, 4.3), PathSeg::LineTo(27.7, 8.3), PathSeg::LineTo(25.7, 10.9), PathSeg::Close], Paint::Gradient(&gradients::SILVER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(10.0, 16.0), PathSeg::CubicTo(10.0, 12.69, 12.69, 10.0, 16.0, 10.0), PathSeg::CubicTo(19.31, 10.0, 22.0, 12.69, 22.0, 16.0), PathSeg::CubicTo(22.0, 19.31, 19.31, 22.0, 16.0, 22.0), PathSeg::CubicTo(12.69, 22.0, 10.0, 19.31, 10.0, 16.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(13.6, 16.0), PathSeg::CubicTo(13.6, 14.67, 14.67, 13.6, 16.0, 13.6), PathSeg::CubicTo(17.33, 13.6, 18.4, 14.67, 18.4, 16.0), PathSeg::CubicTo(18.4, 17.33, 17.33, 18.4, 16.0, 18.4), PathSeg::CubicTo(14.67, 18.4, 13.6, 17.33, 13.6, 16.0), PathSeg::Close], Paint::Gradient(&gradients::DARK), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(11.1, 13.0), PathSeg::CubicTo(11.1, 11.9, 12.62, 11.0, 14.5, 11.0), PathSeg::CubicTo(16.38, 11.0, 17.9, 11.9, 17.9, 13.0), PathSeg::CubicTo(17.9, 14.1, 16.38, 15.0, 14.5, 15.0), PathSeg::CubicTo(12.62, 15.0, 11.1, 14.1, 11.1, 13.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(178),
    Shape::fill(&[PathSeg::MoveTo(7.0, 7.5), PathSeg::CubicTo(7.0, 6.17, 9.69, 5.1, 13.0, 5.1), PathSeg::CubicTo(16.31, 5.1, 19.0, 6.17, 19.0, 7.5), PathSeg::CubicTo(19.0, 8.83, 16.31, 9.9, 13.0, 9.9), PathSeg::CubicTo(9.69, 9.9, 7.0, 8.83, 7.0, 7.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(128),
];

pub(super) const SEARCH: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(19.5, 19.5), PathSeg::LineTo(27.5, 27.5)], Paint::Color(Rgba::rgb(42, 58, 77)), 5.2),
    Shape::line(&[PathSeg::MoveTo(19.5, 19.5), PathSeg::LineTo(27.5, 27.5)], Paint::Color(Rgba::rgb(201, 214, 227)), 3.0),
    Shape::both(&[PathSeg::MoveTo(4.5, 13.0), PathSeg::CubicTo(4.5, 8.31, 8.31, 4.5, 13.0, 4.5), PathSeg::CubicTo(17.69, 4.5, 21.5, 8.31, 21.5, 13.0), PathSeg::CubicTo(21.5, 17.69, 17.69, 21.5, 13.0, 21.5), PathSeg::CubicTo(8.31, 21.5, 4.5, 17.69, 4.5, 13.0), PathSeg::Close], Paint::Color(Rgba::with_alpha(191, 233, 255, 140)), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(4.5, 13.0), PathSeg::CubicTo(4.5, 8.31, 8.31, 4.5, 13.0, 4.5), PathSeg::CubicTo(17.69, 4.5, 21.5, 8.31, 21.5, 13.0), PathSeg::CubicTo(21.5, 17.69, 17.69, 21.5, 13.0, 21.5), PathSeg::CubicTo(8.31, 21.5, 4.5, 17.69, 4.5, 13.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), 2.2),
    Shape::line(&[PathSeg::MoveTo(3.4, 13.0), PathSeg::CubicTo(3.4, 7.7, 7.7, 3.4, 13.0, 3.4), PathSeg::CubicTo(18.3, 3.4, 22.6, 7.7, 22.6, 13.0), PathSeg::CubicTo(22.6, 18.3, 18.3, 22.6, 13.0, 22.6), PathSeg::CubicTo(7.7, 22.6, 3.4, 18.3, 3.4, 13.0), PathSeg::Close], Paint::Color(Rgba::with_alpha(10, 42, 85, 166)), 0.8),
    Shape::fill(&[PathSeg::MoveTo(6.0, 9.5), PathSeg::CubicTo(6.0, 7.84, 8.24, 6.5, 11.0, 6.5), PathSeg::CubicTo(13.76, 6.5, 16.0, 7.84, 16.0, 9.5), PathSeg::CubicTo(16.0, 11.16, 13.76, 12.5, 11.0, 12.5), PathSeg::CubicTo(8.24, 12.5, 6.0, 11.16, 6.0, 9.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(217),
];

pub(super) const HOME: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(22.0, 6.0), PathSeg::LineTo(26.0, 6.0), PathSeg::LineTo(26.0, 14.0), PathSeg::LineTo(22.0, 14.0), PathSeg::Close], Paint::Gradient(&gradients::ORANGE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(7.5, 15.5), PathSeg::LineTo(24.5, 15.5), PathSeg::CubicTo(25.05, 15.5, 25.5, 15.95, 25.5, 16.5), PathSeg::LineTo(25.5, 27.0), PathSeg::CubicTo(25.5, 27.55, 25.05, 28.0, 24.5, 28.0), PathSeg::LineTo(7.5, 28.0), PathSeg::CubicTo(6.95, 28.0, 6.5, 27.55, 6.5, 27.0), PathSeg::LineTo(6.5, 16.5), PathSeg::CubicTo(6.5, 15.95, 6.95, 15.5, 7.5, 15.5), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(2.5, 16.5), PathSeg::LineTo(16.0, 4.5), PathSeg::LineTo(29.5, 16.5), PathSeg::Close], Paint::Gradient(&gradients::RED), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(13.5, 20.5), PathSeg::LineTo(18.5, 20.5), PathSeg::LineTo(18.5, 28.0), PathSeg::LineTo(13.5, 28.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(8.5, 18.5), PathSeg::LineTo(12.0, 18.5), PathSeg::LineTo(12.0, 22.0), PathSeg::LineTo(8.5, 22.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(4.5, 15.5), PathSeg::LineTo(16.0, 6.0), PathSeg::LineTo(27.5, 15.5), PathSeg::CubicTo(19.5, 13.5, 12.5, 13.5, 4.5, 15.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(115),
];

pub(super) const CLOCK: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Paint::Gradient(&gradients::SILVER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(5.7, 16.0), PathSeg::CubicTo(5.7, 10.31, 10.31, 5.7, 16.0, 5.7), PathSeg::CubicTo(21.69, 5.7, 26.3, 10.31, 26.3, 16.0), PathSeg::CubicTo(26.3, 21.69, 21.69, 26.3, 16.0, 26.3), PathSeg::CubicTo(10.31, 26.3, 5.7, 21.69, 5.7, 16.0), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(16.0, 7.0), PathSeg::LineTo(16.0, 9.0), PathSeg::MoveTo(25.0, 16.0), PathSeg::LineTo(23.0, 16.0), PathSeg::MoveTo(16.0, 25.0), PathSeg::LineTo(16.0, 23.0), PathSeg::MoveTo(7.0, 16.0), PathSeg::LineTo(9.0, 16.0)], Paint::Color(Rgba::rgb(42, 90, 149)), 1.0),
    Shape::line(&[PathSeg::MoveTo(16.0, 16.0), PathSeg::LineTo(16.0, 10.0), PathSeg::MoveTo(16.0, 16.0), PathSeg::LineTo(20.5, 18.5)], Paint::Color(Rgba::rgb(10, 42, 85)), 1.4),
    Shape::both(&[PathSeg::MoveTo(14.5, 16.0), PathSeg::CubicTo(14.5, 15.17, 15.17, 14.5, 16.0, 14.5), PathSeg::CubicTo(16.83, 14.5, 17.5, 15.17, 17.5, 16.0), PathSeg::CubicTo(17.5, 16.83, 16.83, 17.5, 16.0, 17.5), PathSeg::CubicTo(15.17, 17.5, 14.5, 16.83, 14.5, 16.0), PathSeg::Close], Paint::Gradient(&gradients::RED), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(7.5, 9.5), PathSeg::CubicTo(7.5, 7.01, 11.31, 5.0, 16.0, 5.0), PathSeg::CubicTo(20.69, 5.0, 24.5, 7.01, 24.5, 9.5), PathSeg::CubicTo(24.5, 11.99, 20.69, 14.0, 16.0, 14.0), PathSeg::CubicTo(11.31, 14.0, 7.5, 11.99, 7.5, 9.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];

pub(super) const MAIL: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.5, 7.5), PathSeg::LineTo(26.5, 7.5), PathSeg::CubicTo(27.6, 7.5, 28.5, 8.4, 28.5, 9.5), PathSeg::LineTo(28.5, 22.5), PathSeg::CubicTo(28.5, 23.6, 27.6, 24.5, 26.5, 24.5), PathSeg::LineTo(5.5, 24.5), PathSeg::CubicTo(4.4, 24.5, 3.5, 23.6, 3.5, 22.5), PathSeg::LineTo(3.5, 9.5), PathSeg::CubicTo(3.5, 8.4, 4.4, 7.5, 5.5, 7.5), PathSeg::Close], Paint::Gradient(&gradients::PAPER), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(4.0, 8.5), PathSeg::LineTo(16.0, 18.0), PathSeg::LineTo(28.0, 8.5)], Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::both(&[PathSeg::MoveTo(21.5, 17.0), PathSeg::LineTo(26.0, 17.0), PathSeg::LineTo(26.0, 21.5), PathSeg::LineTo(21.5, 21.5), PathSeg::Close], Paint::Gradient(&gradients::ORANGE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(5.5, 7.5), PathSeg::LineTo(26.5, 7.5), PathSeg::CubicTo(27.6, 7.5, 28.5, 8.4, 28.5, 9.5), PathSeg::LineTo(28.5, 12.5), PathSeg::CubicTo(20.5, 15.0, 11.5, 15.0, 3.5, 12.5), PathSeg::LineTo(3.5, 9.5), PathSeg::CubicTo(3.5, 8.4, 4.4, 7.5, 5.5, 7.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(102),
];

pub(super) const LOCK: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(10.0, 14.0), PathSeg::LineTo(10.0, 10.0), PathSeg::CubicTo(10.0, 6.69, 12.69, 4.0, 16.0, 4.0), PathSeg::CubicTo(19.31, 4.0, 22.0, 6.69, 22.0, 10.0), PathSeg::LineTo(22.0, 14.0)], Paint::Color(Rgba::rgb(85, 102, 117)), 4.6),
    Shape::line(&[PathSeg::MoveTo(10.0, 14.0), PathSeg::LineTo(10.0, 10.0), PathSeg::CubicTo(10.0, 6.69, 12.69, 4.0, 16.0, 4.0), PathSeg::CubicTo(19.31, 4.0, 22.0, 6.69, 22.0, 10.0), PathSeg::LineTo(22.0, 14.0)], Paint::Color(Rgba::rgb(227, 236, 244)), 2.4),
    Shape::both(&[PathSeg::MoveTo(9.0, 14.0), PathSeg::LineTo(23.0, 14.0), PathSeg::CubicTo(24.66, 14.0, 26.0, 15.34, 26.0, 17.0), PathSeg::LineTo(26.0, 25.0), PathSeg::CubicTo(26.0, 26.66, 24.66, 28.0, 23.0, 28.0), PathSeg::LineTo(9.0, 28.0), PathSeg::CubicTo(7.34, 28.0, 6.0, 26.66, 6.0, 25.0), PathSeg::LineTo(6.0, 17.0), PathSeg::CubicTo(6.0, 15.34, 7.34, 14.0, 9.0, 14.0), PathSeg::Close], Paint::Gradient(&gradients::YELLOW), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(13.8, 20.0), PathSeg::CubicTo(13.8, 18.78, 14.78, 17.8, 16.0, 17.8), PathSeg::CubicTo(17.22, 17.8, 18.2, 18.78, 18.2, 20.0), PathSeg::CubicTo(18.2, 21.22, 17.22, 22.2, 16.0, 22.2), PathSeg::CubicTo(14.78, 22.2, 13.8, 21.22, 13.8, 20.0), PathSeg::Close], Paint::Color(Rgba::rgb(90, 50, 0))),
    Shape::fill(&[PathSeg::MoveTo(15.0, 21.0), PathSeg::LineTo(17.0, 21.0), PathSeg::LineTo(18.0, 25.0), PathSeg::LineTo(14.0, 25.0), PathSeg::Close], Paint::Color(Rgba::rgb(90, 50, 0))),
    Shape::fill(&[PathSeg::MoveTo(8.0, 14.5), PathSeg::LineTo(24.0, 14.5), PathSeg::CubicTo(25.1, 14.5, 26.0, 15.4, 26.0, 16.5), PathSeg::LineTo(26.0, 17.5), PathSeg::CubicTo(19.0, 19.5, 13.0, 19.5, 6.0, 17.5), PathSeg::LineTo(6.0, 16.5), PathSeg::CubicTo(6.0, 15.4, 6.9, 14.5, 8.0, 14.5), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];

pub(super) const HELP: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Paint::Gradient(&gradients::BLUE), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(12.0, 12.0), PathSeg::CubicTo(12.02, 10.06, 13.42, 8.42, 15.33, 8.09), PathSeg::CubicTo(17.24, 7.77, 19.11, 8.86, 19.76, 10.68), PathSeg::CubicTo(20.42, 12.5, 19.68, 14.53, 18.0, 15.5), PathSeg::CubicTo(16.5, 16.5, 16.0, 17.0, 16.0, 18.5)], Paint::Color(Rgba::rgb(255, 255, 255)), 3.0),
    Shape::fill(&[PathSeg::MoveTo(14.2, 24.0), PathSeg::CubicTo(14.2, 23.01, 15.01, 22.2, 16.0, 22.2), PathSeg::CubicTo(16.99, 22.2, 17.8, 23.01, 17.8, 24.0), PathSeg::CubicTo(17.8, 24.99, 16.99, 25.8, 16.0, 25.8), PathSeg::CubicTo(15.01, 25.8, 14.2, 24.99, 14.2, 24.0), PathSeg::Close], Paint::Color(Rgba::rgb(255, 255, 255))),
    Shape::fill(&[PathSeg::MoveTo(6.0, 9.0), PathSeg::CubicTo(6.0, 5.69, 10.48, 3.0, 16.0, 3.0), PathSeg::CubicTo(21.52, 3.0, 26.0, 5.69, 26.0, 9.0), PathSeg::CubicTo(26.0, 12.31, 21.52, 15.0, 16.0, 15.0), PathSeg::CubicTo(10.48, 15.0, 6.0, 12.31, 6.0, 9.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];

pub(super) const WARNING: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(16.0, 3.5), PathSeg::LineTo(29.5, 27.5), PathSeg::LineTo(2.5, 27.5), PathSeg::Close], Paint::Gradient(&gradients::YELLOW), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(16.0, 12.0), PathSeg::LineTo(16.0, 20.0)], Paint::Color(Rgba::rgb(90, 50, 0)), 3.0),
    Shape::fill(&[PathSeg::MoveTo(14.3, 24.0), PathSeg::CubicTo(14.3, 23.06, 15.06, 22.3, 16.0, 22.3), PathSeg::CubicTo(16.94, 22.3, 17.7, 23.06, 17.7, 24.0), PathSeg::CubicTo(17.7, 24.94, 16.94, 25.7, 16.0, 25.7), PathSeg::CubicTo(15.06, 25.7, 14.3, 24.94, 14.3, 24.0), PathSeg::Close], Paint::Color(Rgba::rgb(90, 50, 0))),
    Shape::fill(&[PathSeg::MoveTo(16.0, 5.0), PathSeg::LineTo(23.5, 18.0), PathSeg::CubicTo(18.5, 16.0, 13.5, 16.0, 8.5, 18.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(140),
];

pub(super) const INFO: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Paint::Gradient(&gradients::TEAL), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::fill(&[PathSeg::MoveTo(14.0, 9.5), PathSeg::CubicTo(14.0, 8.4, 14.9, 7.5, 16.0, 7.5), PathSeg::CubicTo(17.1, 7.5, 18.0, 8.4, 18.0, 9.5), PathSeg::CubicTo(18.0, 10.6, 17.1, 11.5, 16.0, 11.5), PathSeg::CubicTo(14.9, 11.5, 14.0, 10.6, 14.0, 9.5), PathSeg::Close], Paint::Color(Rgba::rgb(255, 255, 255))),
    Shape::line(&[PathSeg::MoveTo(16.0, 14.0), PathSeg::LineTo(16.0, 24.0)], Paint::Color(Rgba::rgb(255, 255, 255)), 3.2),
    Shape::fill(&[PathSeg::MoveTo(6.0, 9.0), PathSeg::CubicTo(6.0, 5.69, 10.48, 3.0, 16.0, 3.0), PathSeg::CubicTo(21.52, 3.0, 26.0, 5.69, 26.0, 9.0), PathSeg::CubicTo(26.0, 12.31, 21.52, 15.0, 16.0, 15.0), PathSeg::CubicTo(10.48, 15.0, 6.0, 12.31, 6.0, 9.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(140),
];

pub(super) const ERROR: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Paint::Gradient(&gradients::RED), Paint::Color(Rgba::with_alpha(10, 42, 85, 178)), 0.9),
    Shape::line(&[PathSeg::MoveTo(11.0, 11.0), PathSeg::LineTo(21.0, 21.0), PathSeg::MoveTo(21.0, 11.0), PathSeg::LineTo(11.0, 21.0)], Paint::Color(Rgba::rgb(255, 255, 255)), 3.4),
    Shape::fill(&[PathSeg::MoveTo(6.0, 9.0), PathSeg::CubicTo(6.0, 5.69, 10.48, 3.0, 16.0, 3.0), PathSeg::CubicTo(21.52, 3.0, 26.0, 5.69, 26.0, 9.0), PathSeg::CubicTo(26.0, 12.31, 21.52, 15.0, 16.0, 15.0), PathSeg::CubicTo(10.48, 15.0, 6.0, 12.31, 6.0, 9.0), PathSeg::Close], Paint::Gradient(&gradients::GLOSS)).opacity(153),
];
