// @generated by crates/xui-icons/assets/generate.py from assets/svg/*.svg.
// Do not edit by hand.

use xui_core::backend::PathSeg;

use crate::shape::Shape;
use crate::tone::Tone;

pub(super) const FOLDER: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 8.0), PathSeg::CubicTo(3.0, 6.9, 3.9, 6.0, 5.0, 6.0), PathSeg::LineTo(12.0, 6.0), PathSeg::LineTo(15.0, 9.0), PathSeg::LineTo(27.0, 9.0), PathSeg::CubicTo(28.1, 9.0, 29.0, 9.9, 29.0, 11.0), PathSeg::LineTo(29.0, 25.0), PathSeg::CubicTo(29.0, 26.1, 28.1, 27.0, 27.0, 27.0), PathSeg::LineTo(5.0, 27.0), PathSeg::CubicTo(3.9, 27.0, 3.0, 26.1, 3.0, 25.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(5.5, 19.0), PathSeg::LineTo(7.5, 17.0), PathSeg::LineTo(9.5, 19.0), PathSeg::LineTo(11.5, 17.0), PathSeg::LineTo(13.5, 19.0), PathSeg::LineTo(15.5, 17.0), PathSeg::LineTo(17.5, 19.0), PathSeg::LineTo(19.5, 17.0), PathSeg::LineTo(21.5, 19.0), PathSeg::LineTo(23.5, 17.0), PathSeg::LineTo(25.5, 19.0)], Tone::Rose, 1.6),
    Shape::line(&[PathSeg::MoveTo(5.5, 24.0), PathSeg::LineTo(7.5, 22.0), PathSeg::LineTo(9.5, 24.0), PathSeg::LineTo(11.5, 22.0), PathSeg::LineTo(13.5, 24.0), PathSeg::LineTo(15.5, 22.0), PathSeg::LineTo(17.5, 24.0), PathSeg::LineTo(19.5, 22.0), PathSeg::LineTo(21.5, 24.0), PathSeg::LineTo(23.5, 22.0), PathSeg::LineTo(25.5, 24.0)], Tone::Teal, 1.6),
];

pub(super) const FOLDER_OPEN: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 8.0), PathSeg::CubicTo(3.0, 6.9, 3.9, 6.0, 5.0, 6.0), PathSeg::LineTo(12.0, 6.0), PathSeg::LineTo(15.0, 9.0), PathSeg::LineTo(25.0, 9.0), PathSeg::CubicTo(26.1, 9.0, 27.0, 9.9, 27.0, 11.0), PathSeg::LineTo(27.0, 27.0), PathSeg::LineTo(3.0, 27.0), PathSeg::Close], Tone::Clay, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(2.0, 27.0), PathSeg::LineTo(6.0, 14.0), PathSeg::LineTo(30.0, 14.0), PathSeg::LineTo(26.0, 27.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(8.0, 22.0), PathSeg::LineTo(10.0, 20.0), PathSeg::LineTo(12.0, 22.0), PathSeg::LineTo(14.0, 20.0), PathSeg::LineTo(16.0, 22.0), PathSeg::LineTo(18.0, 20.0), PathSeg::LineTo(20.0, 22.0), PathSeg::LineTo(22.0, 20.0), PathSeg::LineTo(24.0, 22.0)], Tone::Teal, 1.6),
];

pub(super) const DOCUMENT: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(7.0, 3.0), PathSeg::LineTo(20.0, 3.0), PathSeg::LineTo(26.0, 9.0), PathSeg::LineTo(26.0, 29.0), PathSeg::LineTo(7.0, 29.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(20.0, 3.0), PathSeg::LineTo(20.0, 9.0), PathSeg::LineTo(26.0, 9.0)], Tone::Lavender, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(11.0, 14.0), PathSeg::LineTo(22.0, 14.0), PathSeg::MoveTo(11.0, 18.0), PathSeg::LineTo(22.0, 18.0), PathSeg::MoveTo(11.0, 22.0), PathSeg::LineTo(18.0, 22.0)], Tone::Ink, 1.0),
    Shape::line(&[PathSeg::MoveTo(10.0, 26.5), PathSeg::LineTo(12.0, 24.5), PathSeg::LineTo(14.0, 26.5), PathSeg::LineTo(16.0, 24.5), PathSeg::LineTo(18.0, 26.5), PathSeg::LineTo(20.0, 24.5), PathSeg::LineTo(22.0, 26.5)], Tone::Rose, 1.6),
];

pub(super) const IMAGE: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(4.5, 6.0), PathSeg::LineTo(27.5, 6.0), PathSeg::CubicTo(28.33, 6.0, 29.0, 6.67, 29.0, 7.5), PathSeg::LineTo(29.0, 24.5), PathSeg::CubicTo(29.0, 25.33, 28.33, 26.0, 27.5, 26.0), PathSeg::LineTo(4.5, 26.0), PathSeg::CubicTo(3.67, 26.0, 3.0, 25.33, 3.0, 24.5), PathSeg::LineTo(3.0, 7.5), PathSeg::CubicTo(3.0, 6.67, 3.67, 6.0, 4.5, 6.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(6.0, 9.0), PathSeg::LineTo(26.0, 9.0), PathSeg::LineTo(26.0, 23.0), PathSeg::LineTo(6.0, 23.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(18.5, 13.0), PathSeg::CubicTo(18.5, 11.62, 19.62, 10.5, 21.0, 10.5), PathSeg::CubicTo(22.38, 10.5, 23.5, 11.62, 23.5, 13.0), PathSeg::CubicTo(23.5, 14.38, 22.38, 15.5, 21.0, 15.5), PathSeg::CubicTo(19.62, 15.5, 18.5, 14.38, 18.5, 13.0), PathSeg::Close], Tone::Amber),
    Shape::both(&[PathSeg::MoveTo(6.0, 23.0), PathSeg::LineTo(13.0, 14.0), PathSeg::LineTo(18.0, 20.0), PathSeg::LineTo(21.0, 17.0), PathSeg::LineTo(26.0, 23.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const MUSIC: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(13.0, 8.0), PathSeg::LineTo(13.0, 23.0), PathSeg::MoveTo(26.0, 5.0), PathSeg::LineTo(26.0, 21.0)], Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(13.0, 6.0), PathSeg::LineTo(26.0, 3.0), PathSeg::LineTo(26.0, 8.0), PathSeg::LineTo(13.0, 11.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(5.5, 24.0), PathSeg::CubicTo(5.5, 22.34, 7.29, 21.0, 9.5, 21.0), PathSeg::CubicTo(11.71, 21.0, 13.5, 22.34, 13.5, 24.0), PathSeg::CubicTo(13.5, 25.66, 11.71, 27.0, 9.5, 27.0), PathSeg::CubicTo(7.29, 27.0, 5.5, 25.66, 5.5, 24.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(18.5, 21.0), PathSeg::CubicTo(18.5, 19.34, 20.29, 18.0, 22.5, 18.0), PathSeg::CubicTo(24.71, 18.0, 26.5, 19.34, 26.5, 21.0), PathSeg::CubicTo(26.5, 22.66, 24.71, 24.0, 22.5, 24.0), PathSeg::CubicTo(20.29, 24.0, 18.5, 22.66, 18.5, 21.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const ARCHIVE: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.5, 7.0), PathSeg::LineTo(26.5, 7.0), PathSeg::CubicTo(27.33, 7.0, 28.0, 7.67, 28.0, 8.5), PathSeg::LineTo(28.0, 26.5), PathSeg::CubicTo(28.0, 27.33, 27.33, 28.0, 26.5, 28.0), PathSeg::LineTo(5.5, 28.0), PathSeg::CubicTo(4.67, 28.0, 4.0, 27.33, 4.0, 26.5), PathSeg::LineTo(4.0, 8.5), PathSeg::CubicTo(4.0, 7.67, 4.67, 7.0, 5.5, 7.0), PathSeg::Close], Tone::Clay, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(4.5, 4.0), PathSeg::LineTo(27.5, 4.0), PathSeg::CubicTo(28.33, 4.0, 29.0, 4.67, 29.0, 5.5), PathSeg::LineTo(29.0, 9.5), PathSeg::CubicTo(29.0, 10.33, 28.33, 11.0, 27.5, 11.0), PathSeg::LineTo(4.5, 11.0), PathSeg::CubicTo(3.67, 11.0, 3.0, 10.33, 3.0, 9.5), PathSeg::LineTo(3.0, 5.5), PathSeg::CubicTo(3.0, 4.67, 3.67, 4.0, 4.5, 4.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(6.0, 24.0), PathSeg::LineTo(8.0, 22.0), PathSeg::LineTo(10.0, 24.0), PathSeg::LineTo(12.0, 22.0), PathSeg::LineTo(14.0, 24.0), PathSeg::LineTo(16.0, 22.0), PathSeg::LineTo(18.0, 24.0), PathSeg::LineTo(20.0, 22.0), PathSeg::LineTo(22.0, 24.0), PathSeg::LineTo(24.0, 22.0), PathSeg::LineTo(26.0, 24.0)], Tone::Cream, 1.6),
    Shape::fill(&[PathSeg::MoveTo(13.5, 14.0), PathSeg::LineTo(18.5, 14.0), PathSeg::CubicTo(19.33, 14.0, 20.0, 14.67, 20.0, 15.5), PathSeg::LineTo(20.0, 15.5), PathSeg::CubicTo(20.0, 16.33, 19.33, 17.0, 18.5, 17.0), PathSeg::LineTo(13.5, 17.0), PathSeg::CubicTo(12.67, 17.0, 12.0, 16.33, 12.0, 15.5), PathSeg::LineTo(12.0, 15.5), PathSeg::CubicTo(12.0, 14.67, 12.67, 14.0, 13.5, 14.0), PathSeg::Close], Tone::Ink),
];
