// @generated by crates/xui-icons/assets/generate.py from assets/svg/*.svg.
// Do not edit by hand.

use xui_core::backend::PathSeg;

use crate::shape::Shape;
use crate::tone::Tone;

pub(super) const COMPUTER: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(6.0, 4.0), PathSeg::LineTo(26.0, 4.0), PathSeg::CubicTo(27.1, 4.0, 28.0, 4.9, 28.0, 6.0), PathSeg::LineTo(28.0, 20.0), PathSeg::CubicTo(28.0, 21.1, 27.1, 22.0, 26.0, 22.0), PathSeg::LineTo(6.0, 22.0), PathSeg::CubicTo(4.9, 22.0, 4.0, 21.1, 4.0, 20.0), PathSeg::LineTo(4.0, 6.0), PathSeg::CubicTo(4.0, 4.9, 4.9, 4.0, 6.0, 4.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(8.0, 7.0), PathSeg::LineTo(24.0, 7.0), PathSeg::CubicTo(24.55, 7.0, 25.0, 7.45, 25.0, 8.0), PathSeg::LineTo(25.0, 18.0), PathSeg::CubicTo(25.0, 18.55, 24.55, 19.0, 24.0, 19.0), PathSeg::LineTo(8.0, 19.0), PathSeg::CubicTo(7.45, 19.0, 7.0, 18.55, 7.0, 18.0), PathSeg::LineTo(7.0, 8.0), PathSeg::CubicTo(7.0, 7.45, 7.45, 7.0, 8.0, 7.0), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(12.5, 13.0), PathSeg::CubicTo(12.5, 11.07, 14.07, 9.5, 16.0, 9.5), PathSeg::CubicTo(17.93, 9.5, 19.5, 11.07, 19.5, 13.0), PathSeg::CubicTo(19.5, 14.93, 17.93, 16.5, 16.0, 16.5), PathSeg::CubicTo(14.07, 16.5, 12.5, 14.93, 12.5, 13.0), PathSeg::Close], Tone::Teal),
    Shape::line(&[PathSeg::MoveTo(12.5, 13.0), PathSeg::LineTo(19.5, 13.0), PathSeg::MoveTo(16.0, 9.5), PathSeg::CubicTo(14.0, 11.5, 14.0, 14.5, 16.0, 16.5), PathSeg::MoveTo(16.0, 9.5), PathSeg::CubicTo(18.0, 11.5, 18.0, 14.5, 16.0, 16.5)], Tone::Ink, 1.0),
    Shape::both(&[PathSeg::MoveTo(12.0, 22.0), PathSeg::LineTo(20.0, 22.0), PathSeg::LineTo(20.0, 25.0), PathSeg::LineTo(12.0, 25.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(9.0, 25.0), PathSeg::LineTo(23.0, 25.0), PathSeg::CubicTo(23.55, 25.0, 24.0, 25.45, 24.0, 26.0), PathSeg::LineTo(24.0, 27.0), PathSeg::CubicTo(24.0, 27.55, 23.55, 28.0, 23.0, 28.0), PathSeg::LineTo(9.0, 28.0), PathSeg::CubicTo(8.45, 28.0, 8.0, 27.55, 8.0, 27.0), PathSeg::LineTo(8.0, 26.0), PathSeg::CubicTo(8.0, 25.45, 8.45, 25.0, 9.0, 25.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
];

pub(super) const MONITOR: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(7.0, 5.0), PathSeg::LineTo(25.0, 5.0), PathSeg::CubicTo(27.21, 5.0, 29.0, 6.79, 29.0, 9.0), PathSeg::LineTo(29.0, 21.0), PathSeg::CubicTo(29.0, 23.21, 27.21, 25.0, 25.0, 25.0), PathSeg::LineTo(7.0, 25.0), PathSeg::CubicTo(4.79, 25.0, 3.0, 23.21, 3.0, 21.0), PathSeg::LineTo(3.0, 9.0), PathSeg::CubicTo(3.0, 6.79, 4.79, 5.0, 7.0, 5.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(9.5, 8.5), PathSeg::LineTo(22.5, 8.5), PathSeg::CubicTo(24.16, 8.5, 25.5, 9.84, 25.5, 11.5), PathSeg::LineTo(25.5, 18.5), PathSeg::CubicTo(25.5, 20.16, 24.16, 21.5, 22.5, 21.5), PathSeg::LineTo(9.5, 21.5), PathSeg::CubicTo(7.84, 21.5, 6.5, 20.16, 6.5, 18.5), PathSeg::LineTo(6.5, 11.5), PathSeg::CubicTo(6.5, 9.84, 7.84, 8.5, 9.5, 8.5), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(9.0, 18.0), PathSeg::LineTo(12.0, 15.0), PathSeg::LineTo(15.0, 18.0), PathSeg::LineTo(18.0, 15.0), PathSeg::LineTo(21.0, 18.0), PathSeg::LineTo(22.0, 17.0)], Tone::Teal, 1.6),
    Shape::line(&[PathSeg::MoveTo(9.0, 12.0), PathSeg::LineTo(12.0, 11.0)], Tone::Shine, 1.2),
    Shape::fill(&[PathSeg::MoveTo(23.0, 23.5), PathSeg::CubicTo(23.0, 22.95, 23.45, 22.5, 24.0, 22.5), PathSeg::CubicTo(24.55, 22.5, 25.0, 22.95, 25.0, 23.5), PathSeg::CubicTo(25.0, 24.05, 24.55, 24.5, 24.0, 24.5), PathSeg::CubicTo(23.45, 24.5, 23.0, 24.05, 23.0, 23.5), PathSeg::Close], Tone::Rose),
    Shape::both(&[PathSeg::MoveTo(10.0, 25.0), PathSeg::LineTo(22.0, 25.0), PathSeg::LineTo(24.0, 28.0), PathSeg::LineTo(8.0, 28.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
];

pub(super) const KEYBOARD: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(4.0, 9.0), PathSeg::LineTo(28.0, 9.0), PathSeg::CubicTo(29.1, 9.0, 30.0, 9.9, 30.0, 11.0), PathSeg::LineTo(30.0, 22.0), PathSeg::CubicTo(30.0, 23.1, 29.1, 24.0, 28.0, 24.0), PathSeg::LineTo(4.0, 24.0), PathSeg::CubicTo(2.9, 24.0, 2.0, 23.1, 2.0, 22.0), PathSeg::LineTo(2.0, 11.0), PathSeg::CubicTo(2.0, 9.9, 2.9, 9.0, 4.0, 9.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(5.0, 11.5), PathSeg::LineTo(8.0, 11.5), PathSeg::LineTo(8.0, 14.5), PathSeg::LineTo(5.0, 14.5), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(10.0, 11.5), PathSeg::LineTo(13.0, 11.5), PathSeg::LineTo(13.0, 14.5), PathSeg::LineTo(10.0, 14.5), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(15.0, 11.5), PathSeg::LineTo(18.0, 11.5), PathSeg::LineTo(18.0, 14.5), PathSeg::LineTo(15.0, 14.5), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(20.0, 11.5), PathSeg::LineTo(23.0, 11.5), PathSeg::LineTo(23.0, 14.5), PathSeg::LineTo(20.0, 14.5), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(25.0, 11.5), PathSeg::LineTo(28.0, 11.5), PathSeg::LineTo(28.0, 14.5), PathSeg::LineTo(25.0, 14.5), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(7.0, 16.0), PathSeg::LineTo(10.0, 16.0), PathSeg::LineTo(10.0, 19.0), PathSeg::LineTo(7.0, 19.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(12.0, 16.0), PathSeg::LineTo(15.0, 16.0), PathSeg::LineTo(15.0, 19.0), PathSeg::LineTo(12.0, 19.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(17.0, 16.0), PathSeg::LineTo(20.0, 16.0), PathSeg::LineTo(20.0, 19.0), PathSeg::LineTo(17.0, 19.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(22.0, 16.0), PathSeg::LineTo(25.0, 16.0), PathSeg::LineTo(25.0, 19.0), PathSeg::LineTo(22.0, 19.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(9.0, 20.3), PathSeg::LineTo(23.0, 20.3), PathSeg::LineTo(23.0, 22.3), PathSeg::LineTo(9.0, 22.3), PathSeg::Close], Tone::Rose),
];

pub(super) const MOUSE: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(16.0, 4.0), PathSeg::CubicTo(16.0, 1.0, 20.0, 1.0, 22.0, 1.0)], Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(16.0, 4.0), PathSeg::LineTo(16.0, 4.0), PathSeg::CubicTo(19.87, 4.0, 23.0, 7.13, 23.0, 11.0), PathSeg::LineTo(23.0, 21.0), PathSeg::CubicTo(23.0, 24.87, 19.87, 28.0, 16.0, 28.0), PathSeg::LineTo(16.0, 28.0), PathSeg::CubicTo(12.13, 28.0, 9.0, 24.87, 9.0, 21.0), PathSeg::LineTo(9.0, 11.0), PathSeg::CubicTo(9.0, 7.13, 12.13, 4.0, 16.0, 4.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(10.0, 13.4), PathSeg::LineTo(10.0, 11.0), PathSeg::CubicTo(9.98, 7.94, 12.26, 5.36, 15.3, 5.0), PathSeg::LineTo(15.3, 13.4), PathSeg::Close], Tone::Amber),
    Shape::line(&[PathSeg::MoveTo(9.0, 14.0), PathSeg::LineTo(23.0, 14.0), PathSeg::MoveTo(16.0, 4.0), PathSeg::LineTo(16.0, 14.0)], Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(11.0, 22.0), PathSeg::CubicTo(11.0, 24.0, 12.0, 25.0, 13.0, 26.0)], Tone::Shine, 1.2),
];

pub(super) const HARD_DISK: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.0, 10.0), PathSeg::LineTo(27.0, 10.0), PathSeg::CubicTo(28.1, 10.0, 29.0, 10.9, 29.0, 12.0), PathSeg::LineTo(29.0, 22.0), PathSeg::CubicTo(29.0, 23.1, 28.1, 24.0, 27.0, 24.0), PathSeg::LineTo(5.0, 24.0), PathSeg::CubicTo(3.9, 24.0, 3.0, 23.1, 3.0, 22.0), PathSeg::LineTo(3.0, 12.0), PathSeg::CubicTo(3.0, 10.9, 3.9, 10.0, 5.0, 10.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(6.0, 14.0), PathSeg::LineTo(16.0, 14.0), PathSeg::MoveTo(6.0, 17.0), PathSeg::LineTo(16.0, 17.0), PathSeg::MoveTo(6.0, 20.0), PathSeg::LineTo(16.0, 20.0)], Tone::Ink, 1.0),
    Shape::fill(&[PathSeg::MoveTo(22.5, 14.0), PathSeg::CubicTo(22.5, 13.17, 23.17, 12.5, 24.0, 12.5), PathSeg::CubicTo(24.83, 12.5, 25.5, 13.17, 25.5, 14.0), PathSeg::CubicTo(25.5, 14.83, 24.83, 15.5, 24.0, 15.5), PathSeg::CubicTo(23.17, 15.5, 22.5, 14.83, 22.5, 14.0), PathSeg::Close], Tone::Teal),
    Shape::both(&[PathSeg::MoveTo(20.0, 18.0), PathSeg::LineTo(26.0, 18.0), PathSeg::LineTo(26.0, 21.0), PathSeg::LineTo(20.0, 21.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
];

pub(super) const FLOPPY: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(4.0, 4.0), PathSeg::LineTo(25.0, 4.0), PathSeg::LineTo(28.0, 7.0), PathSeg::LineTo(28.0, 28.0), PathSeg::LineTo(4.0, 28.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(9.0, 4.0), PathSeg::LineTo(22.0, 4.0), PathSeg::LineTo(22.0, 12.0), PathSeg::LineTo(9.0, 12.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(17.0, 5.5), PathSeg::LineTo(20.0, 5.5), PathSeg::LineTo(20.0, 10.5), PathSeg::LineTo(17.0, 10.5), PathSeg::Close], Tone::Ink),
    Shape::both(&[PathSeg::MoveTo(8.0, 16.0), PathSeg::LineTo(24.0, 16.0), PathSeg::CubicTo(24.55, 16.0, 25.0, 16.45, 25.0, 17.0), PathSeg::LineTo(25.0, 27.0), PathSeg::CubicTo(25.0, 27.55, 24.55, 28.0, 24.0, 28.0), PathSeg::LineTo(8.0, 28.0), PathSeg::CubicTo(7.45, 28.0, 7.0, 27.55, 7.0, 27.0), PathSeg::LineTo(7.0, 17.0), PathSeg::CubicTo(7.0, 16.45, 7.45, 16.0, 8.0, 16.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(10.0, 20.0), PathSeg::LineTo(22.0, 20.0), PathSeg::MoveTo(10.0, 23.0), PathSeg::LineTo(18.0, 23.0)], Tone::Ink, 1.0),
];

pub(super) const CD_ROM: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(7.0, 16.0), PathSeg::CubicTo(7.0, 11.03, 11.03, 7.0, 16.0, 7.0), PathSeg::CubicTo(20.97, 7.0, 25.0, 11.03, 25.0, 16.0), PathSeg::CubicTo(25.0, 20.97, 20.97, 25.0, 16.0, 25.0), PathSeg::CubicTo(11.03, 25.0, 7.0, 20.97, 7.0, 16.0), PathSeg::Close], Tone::Teal, 3.0),
    Shape::line(&[PathSeg::MoveTo(16.0, 7.0), PathSeg::CubicTo(20.97, 7.0, 25.0, 11.03, 25.0, 16.0)], Tone::Rose, 3.0),
    Shape::line(&[PathSeg::MoveTo(7.0, 16.0), PathSeg::CubicTo(7.0, 13.44, 8.09, 11.01, 10.0, 9.3)], Tone::Amber, 3.0),
    Shape::both(&[PathSeg::MoveTo(12.5, 16.0), PathSeg::CubicTo(12.5, 14.07, 14.07, 12.5, 16.0, 12.5), PathSeg::CubicTo(17.93, 12.5, 19.5, 14.07, 19.5, 16.0), PathSeg::CubicTo(19.5, 17.93, 17.93, 19.5, 16.0, 19.5), PathSeg::CubicTo(14.07, 19.5, 12.5, 17.93, 12.5, 16.0), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(6.0, 12.0), PathSeg::CubicTo(7.12, 9.28, 9.28, 7.12, 12.0, 6.0)], Tone::Shine, 1.2),
];

pub(super) const PRINTER: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(9.0, 4.0), PathSeg::LineTo(23.0, 4.0), PathSeg::LineTo(23.0, 13.0), PathSeg::LineTo(9.0, 13.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(12.0, 7.0), PathSeg::LineTo(20.0, 7.0), PathSeg::MoveTo(12.0, 10.0), PathSeg::LineTo(17.0, 10.0)], Tone::Ink, 1.0),
    Shape::both(&[PathSeg::MoveTo(5.0, 12.0), PathSeg::LineTo(27.0, 12.0), PathSeg::CubicTo(28.1, 12.0, 29.0, 12.9, 29.0, 14.0), PathSeg::LineTo(29.0, 22.0), PathSeg::CubicTo(29.0, 23.1, 28.1, 24.0, 27.0, 24.0), PathSeg::LineTo(5.0, 24.0), PathSeg::CubicTo(3.9, 24.0, 3.0, 23.1, 3.0, 22.0), PathSeg::LineTo(3.0, 14.0), PathSeg::CubicTo(3.0, 12.9, 3.9, 12.0, 5.0, 12.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(8.0, 20.0), PathSeg::LineTo(24.0, 20.0), PathSeg::LineTo(24.0, 29.0), PathSeg::LineTo(8.0, 29.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(11.0, 23.5), PathSeg::LineTo(21.0, 23.5), PathSeg::MoveTo(11.0, 26.0), PathSeg::LineTo(17.0, 26.0)], Tone::Ink, 1.0),
    Shape::fill(&[PathSeg::MoveTo(23.7, 15.5), PathSeg::CubicTo(23.7, 14.78, 24.28, 14.2, 25.0, 14.2), PathSeg::CubicTo(25.72, 14.2, 26.3, 14.78, 26.3, 15.5), PathSeg::CubicTo(26.3, 16.22, 25.72, 16.8, 25.0, 16.8), PathSeg::CubicTo(24.28, 16.8, 23.7, 16.22, 23.7, 15.5), PathSeg::Close], Tone::Rose),
];

pub(super) const MODEM: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(25.0, 14.0), PathSeg::LineTo(25.0, 6.0)], Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(29.0, 2.0), PathSeg::CubicTo(30.33, 3.78, 30.33, 6.22, 29.0, 8.0)], Tone::Shine, 1.2),
    Shape::both(&[PathSeg::MoveTo(23.0, 5.0), PathSeg::CubicTo(23.0, 3.9, 23.9, 3.0, 25.0, 3.0), PathSeg::CubicTo(26.1, 3.0, 27.0, 3.9, 27.0, 5.0), PathSeg::CubicTo(27.0, 6.1, 26.1, 7.0, 25.0, 7.0), PathSeg::CubicTo(23.9, 7.0, 23.0, 6.1, 23.0, 5.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(4.0, 14.0), PathSeg::LineTo(28.0, 14.0), PathSeg::CubicTo(29.1, 14.0, 30.0, 14.9, 30.0, 16.0), PathSeg::LineTo(30.0, 24.0), PathSeg::CubicTo(30.0, 25.1, 29.1, 26.0, 28.0, 26.0), PathSeg::LineTo(4.0, 26.0), PathSeg::CubicTo(2.9, 26.0, 2.0, 25.1, 2.0, 24.0), PathSeg::LineTo(2.0, 16.0), PathSeg::CubicTo(2.0, 14.9, 2.9, 14.0, 4.0, 14.0), PathSeg::Close], Tone::Clay, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(5.6, 20.0), PathSeg::CubicTo(5.6, 19.23, 6.23, 18.6, 7.0, 18.6), PathSeg::CubicTo(7.77, 18.6, 8.4, 19.23, 8.4, 20.0), PathSeg::CubicTo(8.4, 20.77, 7.77, 21.4, 7.0, 21.4), PathSeg::CubicTo(6.23, 21.4, 5.6, 20.77, 5.6, 20.0), PathSeg::Close], Tone::Teal),
    Shape::fill(&[PathSeg::MoveTo(10.1, 20.0), PathSeg::CubicTo(10.1, 19.23, 10.73, 18.6, 11.5, 18.6), PathSeg::CubicTo(12.27, 18.6, 12.9, 19.23, 12.9, 20.0), PathSeg::CubicTo(12.9, 20.77, 12.27, 21.4, 11.5, 21.4), PathSeg::CubicTo(10.73, 21.4, 10.1, 20.77, 10.1, 20.0), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(14.6, 20.0), PathSeg::CubicTo(14.6, 19.23, 15.23, 18.6, 16.0, 18.6), PathSeg::CubicTo(16.77, 18.6, 17.4, 19.23, 17.4, 20.0), PathSeg::CubicTo(17.4, 20.77, 16.77, 21.4, 16.0, 21.4), PathSeg::CubicTo(15.23, 21.4, 14.6, 20.77, 14.6, 20.0), PathSeg::Close], Tone::Rose),
    Shape::line(&[PathSeg::MoveTo(20.0, 22.0), PathSeg::LineTo(21.5, 20.0), PathSeg::LineTo(23.0, 22.0), PathSeg::LineTo(24.5, 20.0), PathSeg::LineTo(26.0, 22.0), PathSeg::LineTo(27.5, 20.0)], Tone::Cream, 1.6),
];

pub(super) const NETWORK: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(10.5, 16.0), PathSeg::CubicTo(10.5, 8.82, 12.96, 3.0, 16.0, 3.0), PathSeg::CubicTo(19.04, 3.0, 21.5, 8.82, 21.5, 16.0), PathSeg::CubicTo(21.5, 23.18, 19.04, 29.0, 16.0, 29.0), PathSeg::CubicTo(12.96, 29.0, 10.5, 23.18, 10.5, 16.0), PathSeg::Close], Tone::Shine, 0.5),
    Shape::line(&[PathSeg::MoveTo(5.5, 16.0), PathSeg::CubicTo(5.5, 8.82, 10.2, 3.0, 16.0, 3.0), PathSeg::CubicTo(21.8, 3.0, 26.5, 8.82, 26.5, 16.0), PathSeg::CubicTo(26.5, 23.18, 21.8, 29.0, 16.0, 29.0), PathSeg::CubicTo(10.2, 29.0, 5.5, 23.18, 5.5, 16.0), PathSeg::Close], Tone::Shine, 0.5),
    Shape::line(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(11.7, 17.33, 20.3, 17.33, 29.0, 16.0), PathSeg::MoveTo(4.9, 9.5), PathSeg::CubicTo(12.3, 10.83, 19.7, 10.83, 27.1, 9.5), PathSeg::MoveTo(4.9, 22.5), PathSeg::CubicTo(12.3, 23.83, 19.7, 23.83, 27.1, 22.5), PathSeg::MoveTo(16.0, 3.0), PathSeg::LineTo(16.0, 29.0)], Tone::Shine, 0.5),
    Shape::both(&[PathSeg::MoveTo(6.5, 9.0), PathSeg::LineTo(8.0, 7.5), PathSeg::LineTo(11.0, 6.8), PathSeg::LineTo(13.5, 7.5), PathSeg::LineTo(14.5, 9.0), PathSeg::LineTo(13.0, 10.0), PathSeg::LineTo(13.5, 11.5), PathSeg::LineTo(12.0, 13.2), PathSeg::LineTo(10.8, 12.6), PathSeg::LineTo(10.0, 14.0), PathSeg::LineTo(8.8, 13.0), PathSeg::LineTo(8.3, 11.0), PathSeg::LineTo(6.6, 10.5), PathSeg::Close], Tone::Teal, Tone::Ink, 0.8),
    Shape::both(&[PathSeg::MoveTo(14.5, 5.5), PathSeg::LineTo(16.5, 5.0), PathSeg::LineTo(17.0, 6.5), PathSeg::LineTo(15.5, 7.5), PathSeg::Close], Tone::Teal, Tone::Ink, 0.8),
    Shape::both(&[PathSeg::MoveTo(10.5, 15.5), PathSeg::LineTo(13.0, 15.0), PathSeg::LineTo(15.0, 16.5), PathSeg::LineTo(14.5, 18.5), PathSeg::LineTo(13.0, 20.0), PathSeg::LineTo(12.6, 22.5), PathSeg::LineTo(11.5, 25.0), PathSeg::LineTo(10.6, 22.5), PathSeg::LineTo(10.2, 19.5), PathSeg::LineTo(9.6, 17.5), PathSeg::Close], Tone::Teal, Tone::Ink, 0.8),
    Shape::both(&[PathSeg::MoveTo(18.5, 12.5), PathSeg::LineTo(21.0, 12.0), PathSeg::LineTo(23.5, 13.2), PathSeg::LineTo(24.8, 15.5), PathSeg::LineTo(23.5, 18.0), PathSeg::LineTo(22.2, 21.0), PathSeg::LineTo(21.0, 23.0), PathSeg::LineTo(19.8, 21.0), PathSeg::LineTo(19.6, 18.0), PathSeg::LineTo(18.4, 16.0), PathSeg::LineTo(17.8, 14.0), PathSeg::Close], Tone::Teal, Tone::Ink, 0.8),
    Shape::both(&[PathSeg::MoveTo(17.5, 8.5), PathSeg::LineTo(19.0, 7.3), PathSeg::LineTo(21.0, 7.5), PathSeg::LineTo(22.5, 8.5), PathSeg::LineTo(21.5, 10.0), PathSeg::LineTo(22.5, 11.0), PathSeg::LineTo(20.0, 11.3), PathSeg::LineTo(18.5, 10.8), PathSeg::Close], Tone::Teal, Tone::Ink, 0.8),
    Shape::line(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Ink, 1.5),
];

pub(super) const SERVER: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.5, 3.0), PathSeg::LineTo(26.5, 3.0), PathSeg::CubicTo(27.33, 3.0, 28.0, 3.67, 28.0, 4.5), PathSeg::LineTo(28.0, 9.5), PathSeg::CubicTo(28.0, 10.33, 27.33, 11.0, 26.5, 11.0), PathSeg::LineTo(5.5, 11.0), PathSeg::CubicTo(4.67, 11.0, 4.0, 10.33, 4.0, 9.5), PathSeg::LineTo(4.0, 4.5), PathSeg::CubicTo(4.0, 3.67, 4.67, 3.0, 5.5, 3.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(5.5, 12.0), PathSeg::LineTo(26.5, 12.0), PathSeg::CubicTo(27.33, 12.0, 28.0, 12.67, 28.0, 13.5), PathSeg::LineTo(28.0, 18.5), PathSeg::CubicTo(28.0, 19.33, 27.33, 20.0, 26.5, 20.0), PathSeg::LineTo(5.5, 20.0), PathSeg::CubicTo(4.67, 20.0, 4.0, 19.33, 4.0, 18.5), PathSeg::LineTo(4.0, 13.5), PathSeg::CubicTo(4.0, 12.67, 4.67, 12.0, 5.5, 12.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(5.5, 21.0), PathSeg::LineTo(26.5, 21.0), PathSeg::CubicTo(27.33, 21.0, 28.0, 21.67, 28.0, 22.5), PathSeg::LineTo(28.0, 27.5), PathSeg::CubicTo(28.0, 28.33, 27.33, 29.0, 26.5, 29.0), PathSeg::LineTo(5.5, 29.0), PathSeg::CubicTo(4.67, 29.0, 4.0, 28.33, 4.0, 27.5), PathSeg::LineTo(4.0, 22.5), PathSeg::CubicTo(4.0, 21.67, 4.67, 21.0, 5.5, 21.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(7.2, 7.0), PathSeg::CubicTo(7.2, 6.28, 7.78, 5.7, 8.5, 5.7), PathSeg::CubicTo(9.22, 5.7, 9.8, 6.28, 9.8, 7.0), PathSeg::CubicTo(9.8, 7.72, 9.22, 8.3, 8.5, 8.3), PathSeg::CubicTo(7.78, 8.3, 7.2, 7.72, 7.2, 7.0), PathSeg::Close], Tone::Teal),
    Shape::fill(&[PathSeg::MoveTo(7.2, 16.0), PathSeg::CubicTo(7.2, 15.28, 7.78, 14.7, 8.5, 14.7), PathSeg::CubicTo(9.22, 14.7, 9.8, 15.28, 9.8, 16.0), PathSeg::CubicTo(9.8, 16.72, 9.22, 17.3, 8.5, 17.3), PathSeg::CubicTo(7.78, 17.3, 7.2, 16.72, 7.2, 16.0), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(7.2, 25.0), PathSeg::CubicTo(7.2, 24.28, 7.78, 23.7, 8.5, 23.7), PathSeg::CubicTo(9.22, 23.7, 9.8, 24.28, 9.8, 25.0), PathSeg::CubicTo(9.8, 25.72, 9.22, 26.3, 8.5, 26.3), PathSeg::CubicTo(7.78, 26.3, 7.2, 25.72, 7.2, 25.0), PathSeg::Close], Tone::Rose),
    Shape::line(&[PathSeg::MoveTo(13.0, 7.0), PathSeg::LineTo(24.0, 7.0), PathSeg::MoveTo(13.0, 16.0), PathSeg::LineTo(24.0, 16.0), PathSeg::MoveTo(13.0, 25.0), PathSeg::LineTo(24.0, 25.0)], Tone::Ink, 1.0),
];

pub(super) const SPEAKER: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(9.0, 3.0), PathSeg::LineTo(23.0, 3.0), PathSeg::CubicTo(24.66, 3.0, 26.0, 4.34, 26.0, 6.0), PathSeg::LineTo(26.0, 26.0), PathSeg::CubicTo(26.0, 27.66, 24.66, 29.0, 23.0, 29.0), PathSeg::LineTo(9.0, 29.0), PathSeg::CubicTo(7.34, 29.0, 6.0, 27.66, 6.0, 26.0), PathSeg::LineTo(6.0, 6.0), PathSeg::CubicTo(6.0, 4.34, 7.34, 3.0, 9.0, 3.0), PathSeg::Close], Tone::Clay, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(12.5, 9.5), PathSeg::CubicTo(12.5, 7.57, 14.07, 6.0, 16.0, 6.0), PathSeg::CubicTo(17.93, 6.0, 19.5, 7.57, 19.5, 9.5), PathSeg::CubicTo(19.5, 11.43, 17.93, 13.0, 16.0, 13.0), PathSeg::CubicTo(14.07, 13.0, 12.5, 11.43, 12.5, 9.5), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(14.6, 9.5), PathSeg::CubicTo(14.6, 8.73, 15.23, 8.1, 16.0, 8.1), PathSeg::CubicTo(16.77, 8.1, 17.4, 8.73, 17.4, 9.5), PathSeg::CubicTo(17.4, 10.27, 16.77, 10.9, 16.0, 10.9), PathSeg::CubicTo(15.23, 10.9, 14.6, 10.27, 14.6, 9.5), PathSeg::Close], Tone::Amber),
    Shape::both(&[PathSeg::MoveTo(10.5, 21.0), PathSeg::CubicTo(10.5, 17.96, 12.96, 15.5, 16.0, 15.5), PathSeg::CubicTo(19.04, 15.5, 21.5, 17.96, 21.5, 21.0), PathSeg::CubicTo(21.5, 24.04, 19.04, 26.5, 16.0, 26.5), PathSeg::CubicTo(12.96, 26.5, 10.5, 24.04, 10.5, 21.0), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(13.5, 21.0), PathSeg::CubicTo(13.5, 19.62, 14.62, 18.5, 16.0, 18.5), PathSeg::CubicTo(17.38, 18.5, 18.5, 19.62, 18.5, 21.0), PathSeg::CubicTo(18.5, 22.38, 17.38, 23.5, 16.0, 23.5), PathSeg::CubicTo(14.62, 23.5, 13.5, 22.38, 13.5, 21.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];
