// @generated by crates/xui-icons/assets/generate.py from assets/svg/*.svg.
// Do not edit by hand.

#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod files;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod hardware;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod system;
#[rustfmt::skip]
#[allow(clippy::approx_constant)] // generated coordinates, not maths
mod toolkit;

use crate::shape::Shape;

/// The groups the set is organised into.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Category {
    /// Computer hardware and peripherals.
    Hardware,
    /// Folders and file types.
    Files,
    /// Everyday operating-system icons.
    System,
    /// Concepts specific to the xui toolkit.
    Toolkit,
}

/// One icon of the Global Village set.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Village {
    /// The `computer` icon.
    Computer,
    /// The `monitor` icon.
    Monitor,
    /// The `keyboard` icon.
    Keyboard,
    /// The `mouse` icon.
    Mouse,
    /// The `hard-disk` icon.
    HardDisk,
    /// The `floppy` icon.
    Floppy,
    /// The `cd-rom` icon.
    CdRom,
    /// The `printer` icon.
    Printer,
    /// The `modem` icon.
    Modem,
    /// The `network` icon.
    Network,
    /// The `server` icon.
    Server,
    /// The `speaker` icon.
    Speaker,
    /// The `folder` icon.
    Folder,
    /// The `folder-open` icon.
    FolderOpen,
    /// The `document` icon.
    Document,
    /// The `image` icon.
    Image,
    /// The `music` icon.
    Music,
    /// The `archive` icon.
    Archive,
    /// The `trash` icon.
    Trash,
    /// The `trash-full` icon.
    TrashFull,
    /// The `settings` icon.
    Settings,
    /// The `search` icon.
    Search,
    /// The `home` icon.
    Home,
    /// The `clock` icon.
    Clock,
    /// The `mail` icon.
    Mail,
    /// The `lock` icon.
    Lock,
    /// The `help` icon.
    Help,
    /// The `warning` icon.
    Warning,
    /// The `info` icon.
    Info,
    /// The `error` icon.
    Error,
    /// The `rpc` icon.
    Rpc,
    /// The `pub-sub` icon.
    PubSub,
    /// The `theme` icon.
    Theme,
    /// The `widget` icon.
    Widget,
    /// The `terminal` icon.
    Terminal,
    /// The `window` icon.
    Window,
}

impl Village {
    /// Every icon, in gallery order.
    pub const ALL: &'static [Village] = &[
        Village::Computer,
        Village::Monitor,
        Village::Keyboard,
        Village::Mouse,
        Village::HardDisk,
        Village::Floppy,
        Village::CdRom,
        Village::Printer,
        Village::Modem,
        Village::Network,
        Village::Server,
        Village::Speaker,
        Village::Folder,
        Village::FolderOpen,
        Village::Document,
        Village::Image,
        Village::Music,
        Village::Archive,
        Village::Trash,
        Village::TrashFull,
        Village::Settings,
        Village::Search,
        Village::Home,
        Village::Clock,
        Village::Mail,
        Village::Lock,
        Village::Help,
        Village::Warning,
        Village::Info,
        Village::Error,
        Village::Rpc,
        Village::PubSub,
        Village::Theme,
        Village::Widget,
        Village::Terminal,
        Village::Window,
    ];

    /// The icon's file stem: `"hard-disk"`, `"pub-sub"`.
    pub fn name(self) -> &'static str {
        match self {
            Village::Computer => "computer",
            Village::Monitor => "monitor",
            Village::Keyboard => "keyboard",
            Village::Mouse => "mouse",
            Village::HardDisk => "hard-disk",
            Village::Floppy => "floppy",
            Village::CdRom => "cd-rom",
            Village::Printer => "printer",
            Village::Modem => "modem",
            Village::Network => "network",
            Village::Server => "server",
            Village::Speaker => "speaker",
            Village::Folder => "folder",
            Village::FolderOpen => "folder-open",
            Village::Document => "document",
            Village::Image => "image",
            Village::Music => "music",
            Village::Archive => "archive",
            Village::Trash => "trash",
            Village::TrashFull => "trash-full",
            Village::Settings => "settings",
            Village::Search => "search",
            Village::Home => "home",
            Village::Clock => "clock",
            Village::Mail => "mail",
            Village::Lock => "lock",
            Village::Help => "help",
            Village::Warning => "warning",
            Village::Info => "info",
            Village::Error => "error",
            Village::Rpc => "rpc",
            Village::PubSub => "pub-sub",
            Village::Theme => "theme",
            Village::Widget => "widget",
            Village::Terminal => "terminal",
            Village::Window => "window",
        }
    }

    /// The group the icon belongs to.
    pub fn category(self) -> Category {
        match self {
            Village::Computer => Category::Hardware,
            Village::Monitor => Category::Hardware,
            Village::Keyboard => Category::Hardware,
            Village::Mouse => Category::Hardware,
            Village::HardDisk => Category::Hardware,
            Village::Floppy => Category::Hardware,
            Village::CdRom => Category::Hardware,
            Village::Printer => Category::Hardware,
            Village::Modem => Category::Hardware,
            Village::Network => Category::Hardware,
            Village::Server => Category::Hardware,
            Village::Speaker => Category::Hardware,
            Village::Folder => Category::Files,
            Village::FolderOpen => Category::Files,
            Village::Document => Category::Files,
            Village::Image => Category::Files,
            Village::Music => Category::Files,
            Village::Archive => Category::Files,
            Village::Trash => Category::System,
            Village::TrashFull => Category::System,
            Village::Settings => Category::System,
            Village::Search => Category::System,
            Village::Home => Category::System,
            Village::Clock => Category::System,
            Village::Mail => Category::System,
            Village::Lock => Category::System,
            Village::Help => Category::System,
            Village::Warning => Category::System,
            Village::Info => Category::System,
            Village::Error => Category::System,
            Village::Rpc => Category::Toolkit,
            Village::PubSub => Category::Toolkit,
            Village::Theme => Category::Toolkit,
            Village::Widget => Category::Toolkit,
            Village::Terminal => Category::Toolkit,
            Village::Window => Category::Toolkit,
        }
    }

    /// The icon's shapes, back to front, on a 32-unit grid.
    pub fn shapes(self) -> &'static [Shape] {
        match self {
            Village::Computer => hardware::COMPUTER,
            Village::Monitor => hardware::MONITOR,
            Village::Keyboard => hardware::KEYBOARD,
            Village::Mouse => hardware::MOUSE,
            Village::HardDisk => hardware::HARD_DISK,
            Village::Floppy => hardware::FLOPPY,
            Village::CdRom => hardware::CD_ROM,
            Village::Printer => hardware::PRINTER,
            Village::Modem => hardware::MODEM,
            Village::Network => hardware::NETWORK,
            Village::Server => hardware::SERVER,
            Village::Speaker => hardware::SPEAKER,
            Village::Folder => files::FOLDER,
            Village::FolderOpen => files::FOLDER_OPEN,
            Village::Document => files::DOCUMENT,
            Village::Image => files::IMAGE,
            Village::Music => files::MUSIC,
            Village::Archive => files::ARCHIVE,
            Village::Trash => system::TRASH,
            Village::TrashFull => system::TRASH_FULL,
            Village::Settings => system::SETTINGS,
            Village::Search => system::SEARCH,
            Village::Home => system::HOME,
            Village::Clock => system::CLOCK,
            Village::Mail => system::MAIL,
            Village::Lock => system::LOCK,
            Village::Help => system::HELP,
            Village::Warning => system::WARNING,
            Village::Info => system::INFO,
            Village::Error => system::ERROR,
            Village::Rpc => toolkit::RPC,
            Village::PubSub => toolkit::PUB_SUB,
            Village::Theme => toolkit::THEME,
            Village::Widget => toolkit::WIDGET,
            Village::Terminal => toolkit::TERMINAL,
            Village::Window => toolkit::WINDOW,
        }
    }
}
