// @generated by crates/xui-icons/assets/generate.py from assets/svg/*.svg.
// Do not edit by hand.

use xui_core::backend::PathSeg;

use crate::shape::Shape;
use crate::tone::Tone;

pub(super) const TRASH: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(13.0, 6.0), PathSeg::LineTo(13.0, 4.0), PathSeg::LineTo(19.0, 4.0), PathSeg::LineTo(19.0, 6.0)], Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(8.0, 10.0), PathSeg::LineTo(24.0, 10.0), PathSeg::LineTo(22.5, 28.0), PathSeg::LineTo(9.5, 28.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(12.0, 13.0), PathSeg::LineTo(12.5, 25.0), PathSeg::MoveTo(16.0, 13.0), PathSeg::LineTo(16.0, 25.0), PathSeg::MoveTo(20.0, 13.0), PathSeg::LineTo(19.5, 25.0)], Tone::Ink, 1.0),
    Shape::both(&[PathSeg::MoveTo(7.0, 6.0), PathSeg::LineTo(25.0, 6.0), PathSeg::CubicTo(25.55, 6.0, 26.0, 6.45, 26.0, 7.0), PathSeg::LineTo(26.0, 9.0), PathSeg::CubicTo(26.0, 9.55, 25.55, 10.0, 25.0, 10.0), PathSeg::LineTo(7.0, 10.0), PathSeg::CubicTo(6.45, 10.0, 6.0, 9.55, 6.0, 9.0), PathSeg::LineTo(6.0, 7.0), PathSeg::CubicTo(6.0, 6.45, 6.45, 6.0, 7.0, 6.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const TRASH_FULL: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(10.0, 8.0), PathSeg::LineTo(11.0, 2.0), PathSeg::LineTo(15.0, 5.0), PathSeg::LineTo(18.0, 1.0), PathSeg::LineTo(21.0, 6.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(8.0, 10.0), PathSeg::LineTo(24.0, 10.0), PathSeg::LineTo(22.5, 28.0), PathSeg::LineTo(9.5, 28.0), PathSeg::Close], Tone::Lavender, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(12.0, 13.0), PathSeg::LineTo(12.5, 25.0), PathSeg::MoveTo(16.0, 13.0), PathSeg::LineTo(16.0, 25.0), PathSeg::MoveTo(20.0, 13.0), PathSeg::LineTo(19.5, 25.0)], Tone::Ink, 1.0),
    Shape::both(&[PathSeg::MoveTo(7.0, 6.0), PathSeg::LineTo(25.0, 6.0), PathSeg::CubicTo(25.55, 6.0, 26.0, 6.45, 26.0, 7.0), PathSeg::LineTo(26.0, 9.0), PathSeg::CubicTo(26.0, 9.55, 25.55, 10.0, 25.0, 10.0), PathSeg::LineTo(7.0, 10.0), PathSeg::CubicTo(6.45, 10.0, 6.0, 9.55, 6.0, 9.0), PathSeg::LineTo(6.0, 7.0), PathSeg::CubicTo(6.0, 6.45, 6.45, 6.0, 7.0, 6.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const SETTINGS: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(26.51, 12.75), PathSeg::LineTo(29.72, 13.22), PathSeg::LineTo(29.72, 18.78), PathSeg::LineTo(26.51, 19.25), PathSeg::LineTo(25.73, 21.13), PathSeg::LineTo(27.67, 23.74), PathSeg::LineTo(23.74, 27.67), PathSeg::LineTo(21.13, 25.73), PathSeg::LineTo(19.25, 26.51), PathSeg::LineTo(18.78, 29.72), PathSeg::LineTo(13.22, 29.72), PathSeg::LineTo(12.75, 26.51), PathSeg::LineTo(10.87, 25.73), PathSeg::LineTo(8.26, 27.67), PathSeg::LineTo(4.33, 23.74), PathSeg::LineTo(6.27, 21.13), PathSeg::LineTo(5.49, 19.25), PathSeg::LineTo(2.28, 18.78), PathSeg::LineTo(2.28, 13.22), PathSeg::LineTo(5.49, 12.75), PathSeg::LineTo(6.27, 10.87), PathSeg::LineTo(4.33, 8.26), PathSeg::LineTo(8.26, 4.33), PathSeg::LineTo(10.87, 6.27), PathSeg::LineTo(12.75, 5.49), PathSeg::LineTo(13.22, 2.28), PathSeg::LineTo(18.78, 2.28), PathSeg::LineTo(19.25, 5.49), PathSeg::LineTo(21.13, 6.27), PathSeg::LineTo(23.74, 4.33), PathSeg::LineTo(27.67, 8.26), PathSeg::LineTo(25.73, 10.87), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(8.0, 16.0), PathSeg::CubicTo(8.0, 11.58, 11.58, 8.0, 16.0, 8.0), PathSeg::CubicTo(20.42, 8.0, 24.0, 11.58, 24.0, 16.0), PathSeg::CubicTo(24.0, 20.42, 20.42, 24.0, 16.0, 24.0), PathSeg::CubicTo(11.58, 24.0, 8.0, 20.42, 8.0, 16.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(12.5, 16.0), PathSeg::CubicTo(12.5, 14.07, 14.07, 12.5, 16.0, 12.5), PathSeg::CubicTo(17.93, 12.5, 19.5, 14.07, 19.5, 16.0), PathSeg::CubicTo(19.5, 17.93, 17.93, 19.5, 16.0, 19.5), PathSeg::CubicTo(14.07, 19.5, 12.5, 17.93, 12.5, 16.0), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(9.0, 13.0), PathSeg::CubicTo(9.8, 11.22, 11.22, 9.8, 13.0, 9.0)], Tone::Shine, 1.2),
];

pub(super) const SEARCH: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(19.0, 19.0), PathSeg::LineTo(27.0, 27.0)], Tone::Ink, 6.0),
    Shape::line(&[PathSeg::MoveTo(19.0, 19.0), PathSeg::LineTo(27.0, 27.0)], Tone::Amber, 3.0),
    Shape::both(&[PathSeg::MoveTo(5.0, 13.0), PathSeg::CubicTo(5.0, 8.58, 8.58, 5.0, 13.0, 5.0), PathSeg::CubicTo(17.42, 5.0, 21.0, 8.58, 21.0, 13.0), PathSeg::CubicTo(21.0, 17.42, 17.42, 21.0, 13.0, 21.0), PathSeg::CubicTo(8.58, 21.0, 5.0, 17.42, 5.0, 13.0), PathSeg::Close], Tone::Mint, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(8.5, 12.0), PathSeg::CubicTo(8.97, 10.3, 10.3, 8.97, 12.0, 8.5)], Tone::Shine, 1.2),
];

pub(super) const HOME: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(22.0, 6.0), PathSeg::LineTo(26.0, 6.0), PathSeg::LineTo(26.0, 14.0), PathSeg::LineTo(22.0, 14.0), PathSeg::Close], Tone::Clay, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(6.0, 15.0), PathSeg::LineTo(26.0, 15.0), PathSeg::LineTo(26.0, 28.0), PathSeg::LineTo(6.0, 28.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(2.0, 16.0), PathSeg::LineTo(16.0, 4.0), PathSeg::LineTo(30.0, 16.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(13.0, 20.0), PathSeg::LineTo(19.0, 20.0), PathSeg::LineTo(19.0, 28.0), PathSeg::LineTo(13.0, 28.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(8.5, 18.0), PathSeg::LineTo(11.5, 18.0), PathSeg::LineTo(11.5, 21.0), PathSeg::LineTo(8.5, 21.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const CLOCK: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(16.0, 5.0), PathSeg::LineTo(16.0, 7.0), PathSeg::MoveTo(27.0, 16.0), PathSeg::LineTo(25.0, 16.0), PathSeg::MoveTo(16.0, 27.0), PathSeg::LineTo(16.0, 25.0), PathSeg::MoveTo(5.0, 16.0), PathSeg::LineTo(7.0, 16.0)], Tone::Ink, 1.0),
    Shape::line(&[PathSeg::MoveTo(16.0, 16.0), PathSeg::LineTo(16.0, 9.0), PathSeg::MoveTo(16.0, 16.0), PathSeg::LineTo(21.0, 19.0)], Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(14.4, 16.0), PathSeg::CubicTo(14.4, 15.12, 15.12, 14.4, 16.0, 14.4), PathSeg::CubicTo(16.88, 14.4, 17.6, 15.12, 17.6, 16.0), PathSeg::CubicTo(17.6, 16.88, 16.88, 17.6, 16.0, 17.6), PathSeg::CubicTo(15.12, 17.6, 14.4, 16.88, 14.4, 16.0), PathSeg::Close], Tone::Rose),
];

pub(super) const MAIL: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.0, 7.0), PathSeg::LineTo(27.0, 7.0), PathSeg::CubicTo(28.1, 7.0, 29.0, 7.9, 29.0, 9.0), PathSeg::LineTo(29.0, 23.0), PathSeg::CubicTo(29.0, 24.1, 28.1, 25.0, 27.0, 25.0), PathSeg::LineTo(5.0, 25.0), PathSeg::CubicTo(3.9, 25.0, 3.0, 24.1, 3.0, 23.0), PathSeg::LineTo(3.0, 9.0), PathSeg::CubicTo(3.0, 7.9, 3.9, 7.0, 5.0, 7.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(3.5, 8.0), PathSeg::LineTo(16.0, 18.0), PathSeg::LineTo(28.5, 8.0)], Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(22.0, 18.0), PathSeg::LineTo(27.0, 18.0), PathSeg::LineTo(27.0, 23.0), PathSeg::LineTo(22.0, 23.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
];

pub(super) const LOCK: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(10.0, 14.0), PathSeg::LineTo(10.0, 10.0), PathSeg::CubicTo(10.0, 6.69, 12.69, 4.0, 16.0, 4.0), PathSeg::CubicTo(19.31, 4.0, 22.0, 6.69, 22.0, 10.0), PathSeg::LineTo(22.0, 14.0)], Tone::Ink, 5.5),
    Shape::line(&[PathSeg::MoveTo(10.0, 14.0), PathSeg::LineTo(10.0, 10.0), PathSeg::CubicTo(10.0, 6.69, 12.69, 4.0, 16.0, 4.0), PathSeg::CubicTo(19.31, 4.0, 22.0, 6.69, 22.0, 10.0), PathSeg::LineTo(22.0, 14.0)], Tone::Lavender, 2.6),
    Shape::both(&[PathSeg::MoveTo(8.0, 14.0), PathSeg::LineTo(24.0, 14.0), PathSeg::CubicTo(25.1, 14.0, 26.0, 14.9, 26.0, 16.0), PathSeg::LineTo(26.0, 26.0), PathSeg::CubicTo(26.0, 27.1, 25.1, 28.0, 24.0, 28.0), PathSeg::LineTo(8.0, 28.0), PathSeg::CubicTo(6.9, 28.0, 6.0, 27.1, 6.0, 26.0), PathSeg::LineTo(6.0, 16.0), PathSeg::CubicTo(6.0, 14.9, 6.9, 14.0, 8.0, 14.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(13.8, 20.0), PathSeg::CubicTo(13.8, 18.78, 14.78, 17.8, 16.0, 17.8), PathSeg::CubicTo(17.22, 17.8, 18.2, 18.78, 18.2, 20.0), PathSeg::CubicTo(18.2, 21.22, 17.22, 22.2, 16.0, 22.2), PathSeg::CubicTo(14.78, 22.2, 13.8, 21.22, 13.8, 20.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(15.0, 21.0), PathSeg::LineTo(17.0, 21.0), PathSeg::LineTo(18.0, 25.0), PathSeg::LineTo(14.0, 25.0), PathSeg::Close], Tone::Ink),
];

pub(super) const HELP: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(12.0, 12.0), PathSeg::CubicTo(12.02, 10.06, 13.42, 8.42, 15.33, 8.09), PathSeg::CubicTo(17.24, 7.77, 19.11, 8.86, 19.76, 10.68), PathSeg::CubicTo(20.42, 12.5, 19.68, 14.53, 18.0, 15.5), PathSeg::CubicTo(16.5, 16.5, 16.0, 17.0, 16.0, 18.5)], Tone::Cream, 3.0),
    Shape::fill(&[PathSeg::MoveTo(14.2, 24.0), PathSeg::CubicTo(14.2, 23.01, 15.01, 22.2, 16.0, 22.2), PathSeg::CubicTo(16.99, 22.2, 17.8, 23.01, 17.8, 24.0), PathSeg::CubicTo(17.8, 24.99, 16.99, 25.8, 16.0, 25.8), PathSeg::CubicTo(15.01, 25.8, 14.2, 24.99, 14.2, 24.0), PathSeg::Close], Tone::Cream),
];

pub(super) const WARNING: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(16.0, 3.0), PathSeg::LineTo(30.0, 28.0), PathSeg::LineTo(2.0, 28.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(16.0, 12.0), PathSeg::LineTo(16.0, 20.0)], Tone::Ink, 3.0),
    Shape::fill(&[PathSeg::MoveTo(14.3, 24.0), PathSeg::CubicTo(14.3, 23.06, 15.06, 22.3, 16.0, 22.3), PathSeg::CubicTo(16.94, 22.3, 17.7, 23.06, 17.7, 24.0), PathSeg::CubicTo(17.7, 24.94, 16.94, 25.7, 16.0, 25.7), PathSeg::CubicTo(15.06, 25.7, 14.3, 24.94, 14.3, 24.0), PathSeg::Close], Tone::Ink),
];

pub(super) const INFO: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(14.0, 9.5), PathSeg::CubicTo(14.0, 8.4, 14.9, 7.5, 16.0, 7.5), PathSeg::CubicTo(17.1, 7.5, 18.0, 8.4, 18.0, 9.5), PathSeg::CubicTo(18.0, 10.6, 17.1, 11.5, 16.0, 11.5), PathSeg::CubicTo(14.9, 11.5, 14.0, 10.6, 14.0, 9.5), PathSeg::Close], Tone::Ink),
    Shape::line(&[PathSeg::MoveTo(16.0, 14.0), PathSeg::LineTo(16.0, 24.0)], Tone::Ink, 3.2),
];

pub(super) const ERROR: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 8.82, 8.82, 3.0, 16.0, 3.0), PathSeg::CubicTo(23.18, 3.0, 29.0, 8.82, 29.0, 16.0), PathSeg::CubicTo(29.0, 23.18, 23.18, 29.0, 16.0, 29.0), PathSeg::CubicTo(8.82, 29.0, 3.0, 23.18, 3.0, 16.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(11.0, 11.0), PathSeg::LineTo(21.0, 21.0), PathSeg::MoveTo(21.0, 11.0), PathSeg::LineTo(11.0, 21.0)], Tone::Chalk, 3.5),
];
