// @generated by crates/xui-icons/assets/generate.py from assets/svg/*.svg.
// Do not edit by hand.

use xui_core::backend::PathSeg;

use crate::shape::Shape;
use crate::tone::Tone;

pub(super) const RPC: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(3.0, 7.0), PathSeg::LineTo(7.0, 7.0), PathSeg::CubicTo(8.1, 7.0, 9.0, 7.9, 9.0, 9.0), PathSeg::LineTo(9.0, 23.0), PathSeg::CubicTo(9.0, 24.1, 8.1, 25.0, 7.0, 25.0), PathSeg::LineTo(3.0, 25.0), PathSeg::CubicTo(1.9, 25.0, 1.0, 24.1, 1.0, 23.0), PathSeg::LineTo(1.0, 9.0), PathSeg::CubicTo(1.0, 7.9, 1.9, 7.0, 3.0, 7.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(25.0, 7.0), PathSeg::LineTo(29.0, 7.0), PathSeg::CubicTo(30.1, 7.0, 31.0, 7.9, 31.0, 9.0), PathSeg::LineTo(31.0, 23.0), PathSeg::CubicTo(31.0, 24.1, 30.1, 25.0, 29.0, 25.0), PathSeg::LineTo(25.0, 25.0), PathSeg::CubicTo(23.9, 25.0, 23.0, 24.1, 23.0, 23.0), PathSeg::LineTo(23.0, 9.0), PathSeg::CubicTo(23.0, 7.9, 23.9, 7.0, 25.0, 7.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(10.0, 8.0), PathSeg::LineTo(18.0, 8.0), PathSeg::LineTo(18.0, 5.0), PathSeg::LineTo(23.0, 9.5), PathSeg::LineTo(18.0, 14.0), PathSeg::LineTo(18.0, 11.0), PathSeg::LineTo(10.0, 11.0), PathSeg::Close], Tone::Amber, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(22.0, 19.0), PathSeg::LineTo(14.0, 19.0), PathSeg::LineTo(14.0, 16.0), PathSeg::LineTo(9.0, 20.5), PathSeg::LineTo(14.0, 25.0), PathSeg::LineTo(14.0, 22.0), PathSeg::LineTo(22.0, 22.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const PUB_SUB: &[Shape] = &[
    Shape::line(&[PathSeg::MoveTo(12.0, 13.0), PathSeg::LineTo(23.0, 8.0), PathSeg::MoveTo(13.0, 16.0), PathSeg::LineTo(23.0, 16.0), PathSeg::MoveTo(12.0, 19.0), PathSeg::LineTo(23.0, 25.0)], Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(15.7, 16.0), PathSeg::CubicTo(15.7, 15.5, 16.1, 15.1, 16.6, 15.1), PathSeg::CubicTo(17.1, 15.1, 17.5, 15.5, 17.5, 16.0), PathSeg::CubicTo(17.5, 16.5, 17.1, 16.9, 16.6, 16.9), PathSeg::CubicTo(16.1, 16.9, 15.7, 16.5, 15.7, 16.0), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(14.55, 20.3), PathSeg::CubicTo(14.55, 19.8, 14.95, 19.4, 15.45, 19.4), PathSeg::CubicTo(15.95, 19.4, 16.35, 19.8, 16.35, 20.3), PathSeg::CubicTo(16.35, 20.8, 15.95, 21.2, 15.45, 21.2), PathSeg::CubicTo(14.95, 21.2, 14.55, 20.8, 14.55, 20.3), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(11.4, 23.45), PathSeg::CubicTo(11.4, 22.95, 11.8, 22.55, 12.3, 22.55), PathSeg::CubicTo(12.8, 22.55, 13.2, 22.95, 13.2, 23.45), PathSeg::CubicTo(13.2, 23.95, 12.8, 24.35, 12.3, 24.35), PathSeg::CubicTo(11.8, 24.35, 11.4, 23.95, 11.4, 23.45), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(7.1, 24.6), PathSeg::CubicTo(7.1, 24.1, 7.5, 23.7, 8.0, 23.7), PathSeg::CubicTo(8.5, 23.7, 8.9, 24.1, 8.9, 24.6), PathSeg::CubicTo(8.9, 25.1, 8.5, 25.5, 8.0, 25.5), PathSeg::CubicTo(7.5, 25.5, 7.1, 25.1, 7.1, 24.6), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(2.8, 23.45), PathSeg::CubicTo(2.8, 22.95, 3.2, 22.55, 3.7, 22.55), PathSeg::CubicTo(4.2, 22.55, 4.6, 22.95, 4.6, 23.45), PathSeg::CubicTo(4.6, 23.95, 4.2, 24.35, 3.7, 24.35), PathSeg::CubicTo(3.2, 24.35, 2.8, 23.95, 2.8, 23.45), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(2.8, 8.55), PathSeg::CubicTo(2.8, 8.05, 3.2, 7.65, 3.7, 7.65), PathSeg::CubicTo(4.2, 7.65, 4.6, 8.05, 4.6, 8.55), PathSeg::CubicTo(4.6, 9.05, 4.2, 9.45, 3.7, 9.45), PathSeg::CubicTo(3.2, 9.45, 2.8, 9.05, 2.8, 8.55), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(7.1, 7.4), PathSeg::CubicTo(7.1, 6.9, 7.5, 6.5, 8.0, 6.5), PathSeg::CubicTo(8.5, 6.5, 8.9, 6.9, 8.9, 7.4), PathSeg::CubicTo(8.9, 7.9, 8.5, 8.3, 8.0, 8.3), PathSeg::CubicTo(7.5, 8.3, 7.1, 7.9, 7.1, 7.4), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(11.4, 8.55), PathSeg::CubicTo(11.4, 8.05, 11.8, 7.65, 12.3, 7.65), PathSeg::CubicTo(12.8, 7.65, 13.2, 8.05, 13.2, 8.55), PathSeg::CubicTo(13.2, 9.05, 12.8, 9.45, 12.3, 9.45), PathSeg::CubicTo(11.8, 9.45, 11.4, 9.05, 11.4, 8.55), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(14.55, 11.7), PathSeg::CubicTo(14.55, 11.2, 14.95, 10.8, 15.45, 10.8), PathSeg::CubicTo(15.95, 10.8, 16.35, 11.2, 16.35, 11.7), PathSeg::CubicTo(16.35, 12.2, 15.95, 12.6, 15.45, 12.6), PathSeg::CubicTo(14.95, 12.6, 14.55, 12.2, 14.55, 11.7), PathSeg::Close], Tone::Amber),
    Shape::both(&[PathSeg::MoveTo(3.0, 16.0), PathSeg::CubicTo(3.0, 13.24, 5.24, 11.0, 8.0, 11.0), PathSeg::CubicTo(10.76, 11.0, 13.0, 13.24, 13.0, 16.0), PathSeg::CubicTo(13.0, 18.76, 10.76, 21.0, 8.0, 21.0), PathSeg::CubicTo(5.24, 21.0, 3.0, 18.76, 3.0, 16.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(23.0, 7.0), PathSeg::CubicTo(23.0, 5.34, 24.34, 4.0, 26.0, 4.0), PathSeg::CubicTo(27.66, 4.0, 29.0, 5.34, 29.0, 7.0), PathSeg::CubicTo(29.0, 8.66, 27.66, 10.0, 26.0, 10.0), PathSeg::CubicTo(24.34, 10.0, 23.0, 8.66, 23.0, 7.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(23.0, 16.0), PathSeg::CubicTo(23.0, 14.34, 24.34, 13.0, 26.0, 13.0), PathSeg::CubicTo(27.66, 13.0, 29.0, 14.34, 29.0, 16.0), PathSeg::CubicTo(29.0, 17.66, 27.66, 19.0, 26.0, 19.0), PathSeg::CubicTo(24.34, 19.0, 23.0, 17.66, 23.0, 16.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(23.0, 25.0), PathSeg::CubicTo(23.0, 23.34, 24.34, 22.0, 26.0, 22.0), PathSeg::CubicTo(27.66, 22.0, 29.0, 23.34, 29.0, 25.0), PathSeg::CubicTo(29.0, 26.66, 27.66, 28.0, 26.0, 28.0), PathSeg::CubicTo(24.34, 28.0, 23.0, 26.66, 23.0, 25.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
];

pub(super) const THEME: &[Shape] = &[
    Shape::fill(&[PathSeg::MoveTo(4.0, 16.0), PathSeg::CubicTo(4.0, 9.37, 9.37, 4.0, 16.0, 4.0), PathSeg::CubicTo(22.63, 4.0, 28.0, 9.37, 28.0, 16.0), PathSeg::CubicTo(28.0, 22.63, 22.63, 28.0, 16.0, 28.0), PathSeg::CubicTo(9.37, 28.0, 4.0, 22.63, 4.0, 16.0), PathSeg::Close], Tone::Amber),
    Shape::fill(&[PathSeg::MoveTo(16.0, 4.0), PathSeg::CubicTo(9.37, 4.0, 4.0, 9.37, 4.0, 16.0), PathSeg::CubicTo(4.0, 22.63, 9.37, 28.0, 16.0, 28.0), PathSeg::Close], Tone::Night),
    Shape::fill(&[PathSeg::MoveTo(9.0, 11.0), PathSeg::CubicTo(9.0, 10.45, 9.45, 10.0, 10.0, 10.0), PathSeg::CubicTo(10.55, 10.0, 11.0, 10.45, 11.0, 11.0), PathSeg::CubicTo(11.0, 11.55, 10.55, 12.0, 10.0, 12.0), PathSeg::CubicTo(9.45, 12.0, 9.0, 11.55, 9.0, 11.0), PathSeg::Close], Tone::Cream),
    Shape::fill(&[PathSeg::MoveTo(11.2, 20.0), PathSeg::CubicTo(11.2, 19.56, 11.56, 19.2, 12.0, 19.2), PathSeg::CubicTo(12.44, 19.2, 12.8, 19.56, 12.8, 20.0), PathSeg::CubicTo(12.8, 20.44, 12.44, 20.8, 12.0, 20.8), PathSeg::CubicTo(11.56, 20.8, 11.2, 20.44, 11.2, 20.0), PathSeg::Close], Tone::Cream),
    Shape::fill(&[PathSeg::MoveTo(6.8, 17.0), PathSeg::CubicTo(6.8, 16.61, 7.11, 16.3, 7.5, 16.3), PathSeg::CubicTo(7.89, 16.3, 8.2, 16.61, 8.2, 17.0), PathSeg::CubicTo(8.2, 17.39, 7.89, 17.7, 7.5, 17.7), PathSeg::CubicTo(7.11, 17.7, 6.8, 17.39, 6.8, 17.0), PathSeg::Close], Tone::Cream),
    Shape::line(&[PathSeg::MoveTo(22.0, 9.0), PathSeg::LineTo(24.0, 7.0), PathSeg::MoveTo(25.0, 16.0), PathSeg::LineTo(28.0, 16.0), PathSeg::MoveTo(22.0, 23.0), PathSeg::LineTo(24.0, 25.0)], Tone::Ink, 1.0),
    Shape::line(&[PathSeg::MoveTo(4.0, 16.0), PathSeg::CubicTo(4.0, 9.37, 9.37, 4.0, 16.0, 4.0), PathSeg::CubicTo(22.63, 4.0, 28.0, 9.37, 28.0, 16.0), PathSeg::CubicTo(28.0, 22.63, 22.63, 28.0, 16.0, 28.0), PathSeg::CubicTo(9.37, 28.0, 4.0, 22.63, 4.0, 16.0), PathSeg::Close], Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(16.0, 4.0), PathSeg::LineTo(16.0, 28.0)], Tone::Ink, 1.5),
];

pub(super) const WIDGET: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(5.0, 4.0), PathSeg::LineTo(19.0, 4.0), PathSeg::CubicTo(20.1, 4.0, 21.0, 4.9, 21.0, 6.0), PathSeg::LineTo(21.0, 9.0), PathSeg::CubicTo(21.0, 10.1, 20.1, 11.0, 19.0, 11.0), PathSeg::LineTo(5.0, 11.0), PathSeg::CubicTo(3.9, 11.0, 3.0, 10.1, 3.0, 9.0), PathSeg::LineTo(3.0, 6.0), PathSeg::CubicTo(3.0, 4.9, 3.9, 4.0, 5.0, 4.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(6.0, 6.5), PathSeg::LineTo(12.0, 6.5)], Tone::Shine, 1.2),
    Shape::both(&[PathSeg::MoveTo(3.0, 14.0), PathSeg::LineTo(10.0, 14.0), PathSeg::LineTo(10.0, 21.0), PathSeg::LineTo(3.0, 21.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(4.5, 17.5), PathSeg::LineTo(6.5, 19.5), PathSeg::LineTo(9.5, 15.5)], Tone::Teal, 2.0),
    Shape::line(&[PathSeg::MoveTo(13.0, 17.5), PathSeg::LineTo(29.0, 17.5)], Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(18.0, 17.5), PathSeg::CubicTo(18.0, 15.84, 19.34, 14.5, 21.0, 14.5), PathSeg::CubicTo(22.66, 14.5, 24.0, 15.84, 24.0, 17.5), PathSeg::CubicTo(24.0, 19.16, 22.66, 20.5, 21.0, 20.5), PathSeg::CubicTo(19.34, 20.5, 18.0, 19.16, 18.0, 17.5), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(5.0, 24.0), PathSeg::LineTo(27.0, 24.0), PathSeg::CubicTo(28.1, 24.0, 29.0, 24.9, 29.0, 26.0), PathSeg::LineTo(29.0, 27.0), PathSeg::CubicTo(29.0, 28.1, 28.1, 29.0, 27.0, 29.0), PathSeg::LineTo(5.0, 29.0), PathSeg::CubicTo(3.9, 29.0, 3.0, 28.1, 3.0, 27.0), PathSeg::LineTo(3.0, 26.0), PathSeg::CubicTo(3.0, 24.9, 3.9, 24.0, 5.0, 24.0), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(5.5, 25.5), PathSeg::LineTo(17.5, 25.5), PathSeg::CubicTo(18.05, 25.5, 18.5, 25.95, 18.5, 26.5), PathSeg::LineTo(18.5, 26.5), PathSeg::CubicTo(18.5, 27.05, 18.05, 27.5, 17.5, 27.5), PathSeg::LineTo(5.5, 27.5), PathSeg::CubicTo(4.95, 27.5, 4.5, 27.05, 4.5, 26.5), PathSeg::LineTo(4.5, 26.5), PathSeg::CubicTo(4.5, 25.95, 4.95, 25.5, 5.5, 25.5), PathSeg::Close], Tone::Teal),
];

pub(super) const TERMINAL: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(4.0, 5.0), PathSeg::LineTo(28.0, 5.0), PathSeg::CubicTo(29.1, 5.0, 30.0, 5.9, 30.0, 7.0), PathSeg::LineTo(30.0, 25.0), PathSeg::CubicTo(30.0, 26.1, 29.1, 27.0, 28.0, 27.0), PathSeg::LineTo(4.0, 27.0), PathSeg::CubicTo(2.9, 27.0, 2.0, 26.1, 2.0, 25.0), PathSeg::LineTo(2.0, 7.0), PathSeg::CubicTo(2.0, 5.9, 2.9, 5.0, 4.0, 5.0), PathSeg::Close], Tone::Screen, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(2.0, 7.0), PathSeg::CubicTo(2.0, 5.9, 2.9, 5.0, 4.0, 5.0), PathSeg::LineTo(28.0, 5.0), PathSeg::CubicTo(29.1, 5.0, 30.0, 5.9, 30.0, 7.0), PathSeg::LineTo(30.0, 11.0), PathSeg::LineTo(2.0, 11.0), PathSeg::Close], Tone::Teal, Tone::Ink, 1.5),
    Shape::fill(&[PathSeg::MoveTo(5.0, 8.0), PathSeg::CubicTo(5.0, 7.45, 5.45, 7.0, 6.0, 7.0), PathSeg::CubicTo(6.55, 7.0, 7.0, 7.45, 7.0, 8.0), PathSeg::CubicTo(7.0, 8.55, 6.55, 9.0, 6.0, 9.0), PathSeg::CubicTo(5.45, 9.0, 5.0, 8.55, 5.0, 8.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(9.0, 8.0), PathSeg::CubicTo(9.0, 7.45, 9.45, 7.0, 10.0, 7.0), PathSeg::CubicTo(10.55, 7.0, 11.0, 7.45, 11.0, 8.0), PathSeg::CubicTo(11.0, 8.55, 10.55, 9.0, 10.0, 9.0), PathSeg::CubicTo(9.45, 9.0, 9.0, 8.55, 9.0, 8.0), PathSeg::Close], Tone::Ink),
    Shape::fill(&[PathSeg::MoveTo(13.0, 8.0), PathSeg::CubicTo(13.0, 7.45, 13.45, 7.0, 14.0, 7.0), PathSeg::CubicTo(14.55, 7.0, 15.0, 7.45, 15.0, 8.0), PathSeg::CubicTo(15.0, 8.55, 14.55, 9.0, 14.0, 9.0), PathSeg::CubicTo(13.45, 9.0, 13.0, 8.55, 13.0, 8.0), PathSeg::Close], Tone::Ink),
    Shape::line(&[PathSeg::MoveTo(7.0, 16.0), PathSeg::LineTo(11.0, 19.0), PathSeg::LineTo(7.0, 22.0)], Tone::Amber, 2.0),
    Shape::line(&[PathSeg::MoveTo(14.0, 23.0), PathSeg::LineTo(22.0, 23.0)], Tone::Cream, 2.0),
];

pub(super) const WINDOW: &[Shape] = &[
    Shape::both(&[PathSeg::MoveTo(4.0, 5.0), PathSeg::LineTo(28.0, 5.0), PathSeg::CubicTo(29.1, 5.0, 30.0, 5.9, 30.0, 7.0), PathSeg::LineTo(30.0, 25.0), PathSeg::CubicTo(30.0, 26.1, 29.1, 27.0, 28.0, 27.0), PathSeg::LineTo(4.0, 27.0), PathSeg::CubicTo(2.9, 27.0, 2.0, 26.1, 2.0, 25.0), PathSeg::LineTo(2.0, 7.0), PathSeg::CubicTo(2.0, 5.9, 2.9, 5.0, 4.0, 5.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(2.0, 7.0), PathSeg::CubicTo(2.0, 5.9, 2.9, 5.0, 4.0, 5.0), PathSeg::LineTo(28.0, 5.0), PathSeg::CubicTo(29.1, 5.0, 30.0, 5.9, 30.0, 7.0), PathSeg::LineTo(30.0, 12.0), PathSeg::LineTo(2.0, 12.0), PathSeg::Close], Tone::Rose, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(4.0, 10.5), PathSeg::LineTo(5.5, 8.5), PathSeg::LineTo(7.0, 10.5), PathSeg::LineTo(8.5, 8.5), PathSeg::LineTo(10.0, 10.5), PathSeg::LineTo(11.5, 8.5), PathSeg::LineTo(13.0, 10.5)], Tone::Cream, 1.6),
    Shape::both(&[PathSeg::MoveTo(22.0, 7.0), PathSeg::LineTo(25.0, 7.0), PathSeg::LineTo(25.0, 10.0), PathSeg::LineTo(22.0, 10.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(26.0, 7.0), PathSeg::LineTo(29.0, 7.0), PathSeg::LineTo(29.0, 10.0), PathSeg::LineTo(26.0, 10.0), PathSeg::Close], Tone::Cream, Tone::Ink, 1.5),
    Shape::both(&[PathSeg::MoveTo(3.5, 14.0), PathSeg::LineTo(10.5, 14.0), PathSeg::LineTo(10.5, 26.0), PathSeg::LineTo(3.5, 26.0), PathSeg::Close], Tone::Cobalt, Tone::Ink, 1.5),
    Shape::line(&[PathSeg::MoveTo(14.0, 16.0), PathSeg::LineTo(26.0, 16.0), PathSeg::MoveTo(14.0, 20.0), PathSeg::LineTo(26.0, 20.0), PathSeg::MoveTo(14.0, 24.0), PathSeg::LineTo(21.0, 24.0)], Tone::Ink, 1.0),
];
