#!/bin/sh
# Regenerates netsurf-sys/generated/ from the upstream commits vendor/ is
# copied from (scripts/revisions).
#
# The NetSurf libraries generate some of their C at build time (gperf, perl
# and libcss's own generator); the crate checks the output in so a cargo build
# needs only a C compiler. Run this after moving a pin (and vendor.sh).
#
# Needs: git, make, cc, perl, gperf, flex, pkg-config and zlib's headers.
# testament.h and shim/ are hand-written and left alone.
set -eu

. "$(dirname "$0")/upstream.sh"
gen=$here/generated
# The NetSurf build system the libraries' makefiles include.
buildsystem_rev=0005ae300283ff01c2e2b05e7376b3e55dea21f7

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
prefix=$work/prefix
export PKG_CONFIG_PATH=$prefix/lib/pkgconfig
# entities.inc is built from a perl hash: fix its order so runs agree.
export PERL_HASH_SEED=0 PERL_PERTURB_KEYS=0

git clone -q https://github.com/netsurf-browser/buildsystem.git "$work/buildsystem"
git -C "$work/buildsystem" checkout -q "$buildsystem_rev"
make -s -C "$work/buildsystem" install PREFIX="$prefix"

# Full upstream checkouts: vendor/ lacks the makefiles and generators.
pins | while read -r repo rev; do
	fetch "$repo" "$rev" "$work/$repo"
done
for lib in libwapcaplet libparserutils libhubbub libcss; do
	make -s -C "$work/$lib" install COMPONENT_TYPE=lib-static \
		PREFIX="$prefix" NSSHARED="$prefix/share/netsurf-buildsystem"
done

mkdir -p "$gen/libparserutils/src/charset" "$gen/libhubbub/src/tokeniser" \
	"$gen/libhubbub/src/treebuilder" "$gen/libcss/src/parse/properties" \
	"$gen/resources"
cp "$work/libparserutils/src/charset/aliases.inc" "$gen/libparserutils/src/charset/"
cp "$work/libhubbub/src/tokeniser/entities.inc" "$gen/libhubbub/src/tokeniser/"
cp "$work/libhubbub/src/treebuilder/autogenerated-element-type.c" "$gen/libhubbub/src/treebuilder/"
rm -f "$gen"/libcss/src/parse/properties/autogenerated_*.c
cp "$work"/libcss/src/parse/properties/autogenerated_*.c "$gen/libcss/src/parse/properties/"

# The English message table, split from FatMessages by NetSurf's own tool.
cc -O2 -I "$work/netsurf" -o "$work/split-messages" \
	"$work/netsurf/tools/split-messages.c" -lz
(cd "$work/netsurf" && "$work/split-messages" -l en -p any -f messages \
	-o "$gen/resources/Messages" resources/FatMessages)

echo "regenerated $gen"
